// js/books-data.js - Données complètes des livres MAURILIVRES

const booksData = [
    // ============================================================
    // ROMANS
    // ============================================================
    {
        id: 1,
        title: "L'Enfant noir",
        author: "Camara Laye",
        price: 400,
        category: "roman",
        image: "images/books/camara-laye.jpg",
        isNew: true,
        isBestseller: true,
        description: "Autobiographie d'une enfance en Haute-Guinée.",
        resume: "LES GRANDS TEXTES DU XXe SIÈCLE L'enfant noir grandit dans un village de Haute-Guinée où le merveilleux côtoie quotidiennement la réalité. Son père, forgeron, travaille l'or au rythme de la harpe des griots et des incantations aux génies du feu et du vent. Respectée de tous, sa mère jouit de mystérieux pouvoirs sur les êtres et les choses. Elle sait détourner les sortilèges et tenir à l'écart les crocodiles du fleuve Niger. Aîné de la famille, le petit garçon est destiné à prendre la relève de son père à l'atelier et, surtout, à perpétuer l'esprit de sa caste au sein du village. Mais son puissant désir d'apprendre l'entraînera inéluctablement vers d'autres horizons, loin des traditions et des coutumes de son peuple. Un livre intemporel qui s'est imposé comme un classique de notre temps.",
        details: {
            ean: "9782266178945",
            isbn: "2266178946",
            contributeurs: "Camara Laye (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pocket",
            collection: "Best",
            largeur: "10.9 cm",
            longueur: "17.8 cm",
            epaisseur: "1.4 cm",
            poids: "0.129 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Littérature francophone"
        }
    },
    {
        id: 2,
        title: "Marche ou crève",
        author: "Stephen King",
        price: 600,
        category: "roman",
        image: "images/books/marche-ou-creve.jpg",
        isNew: true,
        isBestseller: false,
        description: "Cent adolescents en marche forcée.",
        resume: "Garraty, un jeune adolescent natif du Maine, va concourir pour « La Longue Marche », une compétition qui compte cent participants. La règle est simple : marcher sans jamais s'arrêter. Celui qui ralentit ou s'arrête est éliminé... définitivement. Une course contre la montre haletante où chaque pas peut être le dernier.",
        details: {
            ean: "9782290308370",
            isbn: "2290308374",
            contributeurs: "Stephen King (Auteur principal)",
            format: "Livre poche",
            nbPages: 400,
            editeur: "J'ai lu",
            collection: "Thriller",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.8 cm",
            poids: "0.220 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Thriller"
        }
    },
    {
        id: 3,
        title: "Priére aux vivants pour leur pardonner d'être vivants",
        author: "Charlotte Delbo",
        price: 500,
        category: "roman",
        image: "images/books/charlotte.jpg",
        isNew: false,
        isBestseller: true,
        description: "Vie tragique de Charlotte Salomon.",
        resume: "Charlotte Salomon, artiste peintre morte à vingt-six ans alors qu'elle était enceinte. Après une enfance à Berlin marquée par une tragédie familiale, Charlotte est exclue progressivement par les nazis de toutes les sphères de la société allemande. Un roman poignant sur la vie d'une artiste juive pendant la Seconde Guerre mondiale.",
        details: {
            ean: "9782070458356",
            isbn: "2070458351",
            contributeurs: "David Foenkinos (Auteur principal)",
            format: "Livre poche",
            nbPages: 256,
            editeur: "Gallimard",
            collection: "Folio",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.150 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Littérature française"
        }
    },
    {
        id: 4,
        title: "La Femme de ménage",
        author: "Freida McFadden",
        price: 600,
        category: "roman",
        image: "images/books/femme-menage.jpg",
        isNew: true,
        isBestseller: true,
        description: "Millie découvre des secrets sombres.",
        resume: "Chaque jour, Millie fait le ménage dans la belle maison des Winchester, une riche famille new-yorkaise. Elle récupère aussi leur fille à l'école et prépare les repas. Mais Millie découvre peu à peu des secrets sombres qui se cachent derrière les murs de cette maison. Un thriller psychologique captivant.",
        details: {
            ean: "9782290391174",
            isbn: "2290391174",
            contributeurs: "Freida McFadden (Auteur principal)",
            format: "Livre poche",
            nbPages: 416,
            editeur: "J'ai lu",
            collection: "Thriller",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.6 cm",
            poids: "0.210 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Thriller psychologique"
        }
    },
    {
        id: 5,
        title: "Nos étoiles contraires",
        author: "John Green",
        price: 600,
        category: "roman",
        image: "images/books/nos-etoiles-contraires.jpg",
        isNew: true,
        isBestseller: true,
        description: "Hazel et Augustus.",
        resume: "Hazel, 16 ans, est atteinte d'un cancer. Son dernier traitement semble avoir arrêté l'évolution de la maladie, mais elle se sait condamnée. Elle rencontre Augustus, un jeune homme atteint d'un cancer également, et une histoire d'amour bouleversante naît entre eux. Un roman poignant sur la vie, la mort et l'amour.",
        details: {
            ean: "9782092552300",
            isbn: "2092552307",
            contributeurs: "John Green (Auteur principal), Catherine Gibert (Traducteur)",
            format: "Livre poche",
            nbPages: 330,
            editeur: "Nathan",
            collection: "Littérature jeunesse",
            largeur: "14 cm",
            longueur: "21 cm",
            epaisseur: "1.8 cm",
            poids: "0.320 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Roman jeunesse"
        }
    },
    {
        id: 6,
        title: "Mille et un je",
        author: "Mariam Derwich",
        price: 300,
        category: "poésie",
        image: "images/books/mille-en-un.jpg",
        isNew: true,
        isBestseller: false,
        description: "Recueil de poésie.",
        resume: "Métisse de père mauritanien et de mère française, Marième Mint Derwich dit rêver d'une Mauritanie arc-en-ciel. Son recueil 'Mille et un Je' est une invitation à la réflexion sur l'identité, le métissage et la condition de la femme mauritanienne.",
        details: {
            ean: "9782343152105",
            isbn: "2343152109",
            contributeurs: "Mariam Derwich (Auteur principal)",
            format: "Livre broché",
            nbPages: 120,
            editeur: "Editions de la Librairie 15/21",
            collection: "Lettres Mauritaniennes",
            largeur: "13.5 cm",
            longueur: "21.5 cm",
            epaisseur: "1 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Poésie, Littérature mauritanienne"
        }
    },
    {
        id: 7,
        title: "Les Chroniques de Narnia",
        author: "C.S. Lewis",
        price: 700,
        category: "jeunesse",
        image: "images/books/narnia.jpg",
        isNew: true,
        isBestseller: true,
        description: "Quatre enfants libèrent Narnia.",
        resume: "Les frères et sœurs Peter, Susan, Edmund et Lucy ont été envoyés à la campagne afin qu'ils échappent aux bombardements, chez un vieux professeur. C'est là qu'ils découvrent un monde magique appelé Narnia, où les animaux parlent et où la magie existe. Une aventure fantastique qui a marqué des générations.",
        details: {
            ean: "9782070659142",
            isbn: "2070659144",
            contributeurs: "C.S. Lewis (Auteur principal)",
            format: "Livre broché",
            nbPages: 800,
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.5 cm",
            longueur: "18 cm",
            epaisseur: "2.5 cm",
            poids: "0.400 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Fantasy"
        }
    },
    {
        id: 8,
        title: "La Sélection",
        author: "Kiera Cass",
        price: 550,
        category: "roman",
        image: "images/books/la-selection.jpg",
        isNew: true,
        isBestseller: false,
        description: "America Singer.",
        resume: "35 candidates. 1 couronne. La compétition de leur vie. Pour les jeunes filles choisies, la Sélection représente une chance unique de troquer un destin. Dans un futur sombre, sur les ruines des États-Unis, un jeu... La compétition de leur vie pour gagner le cœur du prince.",
        details: {
            ean: "9782266260580",
            isbn: "2266260588",
            contributeurs: "Kiera Cass (Auteur principal)",
            format: "Livre poche",
            nbPages: 384,
            editeur: "Pocket Jeunesse",
            collection: "Pocket Jeunesse",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.8 cm",
            poids: "0.230 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Romance"
        }
    },
    {
        id: 9,
        title: "Vampire Academy",
        author: "Richelle Mead",
        price: 600,
        category: "roman",
        image: "images/books/vampire-academy.jpg",
        isNew: true,
        isBestseller: false,
        description: "Rose protège Lissa.",
        resume: "Rose Hathaway est une Dhampir, vouée à protéger les vampires Moroï. Son amie Lissa est une princesse Moroï. Ensemble, elles tentent de survivre dans un monde où les dangers sont partout. Un best-seller international adapté au cinéma.",
        details: {
            ean: "9782266215429",
            isbn: "2266215426",
            contributeurs: "Richelle Mead (Auteur principal)",
            format: "Livre poche",
            nbPages: 480,
            editeur: "Pocket Jeunesse",
            collection: "Pocket Jeunesse",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.8 cm",
            poids: "0.250 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Fantasy"
        }
    },
    {
        id: 10,
        title: "Le livre des étoiles",
        author: "Erik L'Homme",
        price: 500,
        category: "roman",
        image: "images/books/livre-etoiles.jpg",
        isNew: true,
        isBestseller: false,
        description: "Robin et Qadehar.",
        resume: "Guillemot de Troïl est un garçon du pays d'Ys, situé à mi-chemin entre le Monde Réel et le Monde Incertain. D'où lui viennent ses dons pour la sorcellerie ? Une trilogie de fantasy pour la jeunesse qui a marqué toute une génération.",
        details: {
            ean: "9782070545810",
            isbn: "2070545815",
            contributeurs: "Erik L'Homme (Auteur principal)",
            format: "Livre poche",
            nbPages: 252,
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.5 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Fantasy jeunesse"
        }
    },
    {
        id: 11,
        title: "Comme toi",
        author: "Lisa Jewell",
        price: 1000,
        category: "roman",
        image: "images/books/comme-toi.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une fillette au visage d'une disparue.",
        resume: "Trois cadavres et un bébé abandonné : c'est la macabre découverte que fait la police dans une demeure de Chelsea. Faute de preuves, on privilégie la piste d'un suicide collectif et l'affaire est classée. Dix ans plus tard, Ellie, disparue à l'âge de quinze ans, refait surface... Ou plutôt, une jeune fille qui lui ressemble étrangement.",
        details: {
            ean: "9782381960054",
            isbn: "2381960058",
            contributeurs: "Lisa Jewell (Auteur principal)",
            format: "Livre broché",
            nbPages: 480,
            editeur: "Hauteville",
            collection: "Hauteville Thriller",
            largeur: "14 cm",
            longueur: "21 cm",
            epaisseur: "2.5 cm",
            poids: "0.480 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Thriller"
        }
    },
    {
        id: 12,
        title: "Le prince de la brume",
        author: "Carlos Ruiz Zafón",
        price: 550,
        category: "roman",
        image: "images/books/prince-brume.jpg",
        isNew: true,
        isBestseller: false,
        description: "Max et le Prince de la Brume.",
        resume: "1943, Angleterre. Fuyant la guerre, la famille Carver se réfugie dans un village de bord de mer. Max, le fils aîné, découvre un jardin rempli de statues étranges et un mystérieux personnage : le Prince de la Brume. Un roman d'horreur et de mystère pour adolescents.",
        details: {
            ean: "9782747038917",
            isbn: "2747038919",
            contributeurs: "Carlos Ruiz Zafón (Auteur principal)",
            format: "Livre poche",
            nbPages: 280,
            editeur: "Bayard Jeunesse",
            collection: "Bayard Jeunesse",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.200 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Horreur"
        }
    },
    {
        id: 13,
        title: "Oksa Pollock",
        author: "Anne Plichota",
        price: 600,
        category: "roman",
        image: "images/books/oksa-pollock.jpg",
        isNew: true,
        isBestseller: false,
        description: "Oksa et ses dons.",
        resume: "Oksa Pollock, 13 ans, pensait être comme tout le monde, mais ce soir tout a changé. Un peu angoissée par la rentrée dans son nouveau collège, Oksa déclenche tout à coup des phénomènes étranges dans sa chambre. Un coin de son bureau prend feu... Une série fantasy qui a conquis des milliers de lecteurs.",
        details: {
            ean: "9782075102436",
            isbn: "2075102430",
            contributeurs: "Anne Plichota, Cendrine Wolf (Auteurs principaux)",
            format: "Livre poche",
            nbPages: 380,
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.5 cm",
            longueur: "18 cm",
            epaisseur: "1.8 cm",
            poids: "0.280 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Fantasy"
        }
    },
    {
        id: 14,
        title: "Meurtre mode d'emploi",
        author: "Holly Jackson",
        price: 650,
        category: "roman",
        image: "images/books/meurtre-mode-emploi.jpg",
        isNew: true,
        isBestseller: false,
        description: "Pip enquête.",
        resume: "Il y a cinq ans, Sal Singh s'est accusé du meurtre de sa petite amie, Andie Bell, avant de se donner la mort. La police est sûre que l'affaire est résolue. Toute la ville aussi. Mais Pippa, une lycéenne de 17 ans passionnée par le true crime, décide de mener sa propre enquête.",
        details: {
            ean: "9782203225756",
            isbn: "2203225752",
            contributeurs: "Holly Jackson (Auteur principal)",
            format: "Livre broché",
            nbPages: 522,
            editeur: "Casterman",
            collection: "Casterman",
            largeur: "14 cm",
            longueur: "22 cm",
            epaisseur: "2.5 cm",
            poids: "0.520 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Thriller jeunesse"
        }
    },
    {
        id: 15,
        title: "L'Arbre à la cour criminelle",
        author: "Djibril Hamet Ly",
        price: 300,
        category: "théatre",
        image: "images/books/arbre-cours.jpg",
        isNew: true,
        isBestseller: false,
        description: "Enquête en Sologne.",
        resume: "Une pièce de théâtre captivante qui explore les thèmes de la justice, de la tradition et de la modernité en Mauritanie. L'arbre à la cour criminelle est le témoin silencieux des drames humains qui se jouent sous ses branches.",
        details: {
            ean: "9782343178907",
            isbn: "2343178906",
            contributeurs: "Djibril Hamet Ly (Auteur principal)",
            format: "Livre broché",
            nbPages: 120,
            editeur: "Editions L'Harmattan",
            collection: "Études africaines",
            largeur: "13.5 cm",
            longueur: "21.5 cm",
            epaisseur: "1 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Théâtre, Littérature africaine"
        }
    },
    {
        id: 16,
        title: "Je veux parler",
        author: "Djibril zakaria sall",
        price: 300,
        category: "poésie",
        image: "images/books/je-veux-parler.jpg",
        isNew: true,
        isBestseller: false,
        description: "28 nouvelles-poésies.",
        resume: "Ancien commissaire de police, Djibril Zakaria Sall faisait des dictées à ses prisonniers. Son recueil de poésies 'Je veux parler' est une anthologie poétique qui couvre la période 1967-2012. Une voix unique de la littérature mauritanienne.",
        details: {
            ean: "9782343172356",
            isbn: "2343172357",
            contributeurs: "Djibril Zakaria Sall (Auteur principal)",
            format: "Livre broché",
            nbPages: 167,
            editeur: "Editions de la Librairie 15/21",
            collection: "Lettres Mauritaniennes",
            largeur: "13.5 cm",
            longueur: "21.5 cm",
            epaisseur: "1 cm",
            poids: "0.200 kg",
            impression: "Non",
            categories: "Livres, Poésie, Littérature mauritanienne"
        }
    },

    // ============================================================
    // DÉVELOPPEMENT PERSONNEL
    // ============================================================
    {
        id: 17,
        title: "L'autoroute du millionnaire",
        author: "MJ DeMarco",
        price: 2000,
        category: "developpement",
        image: "images/books/autoroute-millionnaire.jpg",
        isNew: true,
        isBestseller: true,
        description: "Devenez riche rapidement.",
        resume: "L’Autoroute du millionnaire est un livre qui remet en question les croyances traditionnelles sur la richesse. MJ DeMarco, multimillionnaire autodidacte, expose sa vision : la voie rapide vers la liberté financière passe par l'entrepreneuriat et la création de valeur, non par l'épargne et la retraite.",
        details: {
            ean: "9782897811903",
            isbn: "2897811906",
            contributeurs: "MJ DeMarco (Auteur principal)",
            format: "Livre broché",
            nbPages: 400,
            editeur: "Un Monde Différent",
            collection: "Développement personnel",
            largeur: "15 cm",
            longueur: "23 cm",
            epaisseur: "2.5 cm",
            poids: "0.600 kg",
            impression: "Non",
            categories: "Livres, Développement personnel, Finance"
        }
    },
    {
        id: 18,
        title: "Père riche, père pauvre",
        author: "Robert Kiyosaki",
        price: 2500,
        category: "developpement",
        image: "images/books/pere-riche-pere-pauvre.jpg",
        isNew: true,
        isBestseller: true,
        description: "Les clés de la réussite financière.",
        resume: "Père riche, père pauvre est un best-seller mondial qui brise le mythe selon lequel il faut gagner beaucoup d'argent pour devenir riche. Robert Kiyosaki propose un parallèle entre la mentalité d'un père riche et celle d'un père pauvre, et enseigne les principes de l'éducation financière.",
        details: {
            ean: "9782081517017",
            isbn: "2081517019",
            contributeurs: "Robert T. Kiyosaki (Auteur principal)",
            format: "Livre broché",
            nbPages: 300,
            editeur: "Maxima",
            collection: "Développement personnel",
            largeur: "15 cm",
            longueur: "23 cm",
            epaisseur: "2 cm",
            poids: "0.450 kg",
            impression: "Non",
            categories: "Livres, Développement personnel, Finance"
        }
    },
    {
        id: 19,
        title: "Réfléchissez et devenez riche",
        author: "Napoleon Hill",
        price: 2000,
        category: "developpement",
        image: "images/books/reflechissez-devenez-riche.jpg",
        isNew: true,
        isBestseller: true,
        description: "Les 13 principes de la réussite.",
        resume: "Réfléchissez et devenez riche est un classique du développement personnel. Napoleon Hill y développe treize principes universels pour atteindre la réussite, basés sur des interviews de plus de 500 personnes riches et célèbres.",
        details: {
            ean: "9782897818322",
            isbn: "2897818323",
            contributeurs: "Napoleon Hill (Auteur principal)",
            format: "Livre broché",
            nbPages: 320,
            editeur: "Un Monde Différent",
            collection: "Développement personnel",
            largeur: "15 cm",
            longueur: "23 cm",
            epaisseur: "2 cm",
            poids: "0.480 kg",
            impression: "Non",
            categories: "Livres, Développement personnel, Motivation"
        }
    },
    {
        id: 20,
        title: "Atomic Habits",
        author: "James Clear",
        price: 1500,
        category: "developpement",
        image: "images/books/atomic-habits.jpg",
        isNew: true,
        isBestseller: true,
        description: "Changez vos habitudes.",
        resume: "Atomic Habits est un guide pratique pour former de bonnes habitudes et se débarrasser des mauvaises. James Clear, expert mondial en matière de formation des habitudes, propose des stratégies concrètes pour réussir à changer durablement son comportement.",
        details: {
            ean: "9782100867192",
            isbn: "2100867197",
            contributeurs: "James Clear (Auteur principal)",
            format: "Livre broché",
            nbPages: 320,
            editeur: "Dunod",
            collection: "Développement personnel",
            largeur: "15 cm",
            longueur: "23 cm",
            epaisseur: "2 cm",
            poids: "0.450 kg",
            impression: "Non",
            categories: "Livres, Développement personnel, Habitudes"
        }
    },
    {
        id: 21,
        title: "Les 4 accords toltèques",
        author: "Don Miguel Ruiz",
        price: 600,
        category: "developpement",
        image: "images/books/4-accords-tolteques.jpg",
        isNew: true,
        isBestseller: false,
        description: "Sagesse toltèque.",
        resume: "Dans ce livre, Don Miguel Ruiz révèle la source des croyances limitatrices qui nous privent de joie et créent des souffrances inutiles. Il montre en des termes très clairs comment appliquer les quatre accords toltèques pour se libérer et retrouver l'amour inconditionnel et la liberté personnelle.",
        details: {
            ean: "9782702912436",
            isbn: "2702912438",
            contributeurs: "Don Miguel Ruiz (Auteur principal)",
            format: "Livre poche",
            nbPages: 160,
            editeur: "J'ai lu",
            collection: "J'ai lu Bien-être",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1 cm",
            poids: "0.100 kg",
            impression: "Non",
            categories: "Livres, Développement personnel, Spiritualité"
        }
    },
    {
        id: 22,
        title: "L'Art subtil de s'en foutre",
        author: "Mark Manson",
        price: 1000,
        category: "developpement",
        image: "images/books/art-subtil-sen-foutre.webp",
        isNew: true,
        isBestseller: true,
        description: "Choisissez vos combats.",
        resume: "Mark Manson invite à un moment de parler vrai en mode je-te-regarde-dans-les-yeux, fait d'histoires vécues et d'humour potache. Un livre-manifeste pour construire des vies plus réjouissantes, plus ancrées. 'S'en foutre ne signifie pas être indifférent, mais être à l'aise avec le sentiment d'être différent'.",
        details: {
            ean: "9782290135655",
            isbn: "2290135657",
            contributeurs: "Mark Manson (Auteur principal)",
            format: "Livre poche",
            nbPages: 256,
            editeur: "J'ai lu",
            collection: "J'ai lu Bien-être",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.160 kg",
            impression: "Non",
            categories: "Livres, Développement personnel, Philosophie"
        }
    },
    {
        id: 23,
        title: "Les 7 habitudes des gens efficaces",
        author: "Stephen Covey",
        price: 1500,
        category: "developpement",
        image: "images/books/7-habitudes.webp",
        isNew: true,
        isBestseller: false,
        description: "Management et productivité.",
        resume: "Les 7 habitudes des gens efficaces est un classique du management. Stephen Covey y présente une approche de la croissance personnelle et professionnelle basée sur des principes intemporels. Le programme des Sept Habitudes fournit des pistes de réflexion et des exercices pour tirer le meilleur parti de soi-même.",
        details: {
            ean: "9782750102007",
            isbn: "2750102008",
            contributeurs: "Stephen R. Covey (Auteur principal)",
            format: "Livre broché",
            nbPages: 400,
            editeur: "First",
            collection: "Développement personnel",
            largeur: "15 cm",
            longueur: "23 cm",
            epaisseur: "2.5 cm",
            poids: "0.550 kg",
            impression: "Non",
            categories: "Livres, Développement personnel, Management"
        }
    },
    {
        id: 24,
        title: "La Semaine de 4 heures",
        author: "Tim Ferriss",
        price: 600,
        category: "developpement",
        image: "images/books/semaine-4-heures.webp",
        isNew: true,
        isBestseller: false,
        description: "Vivez mieux en travaillant moins.",
        resume: "La Semaine de 4 heures est un véritable manifeste pour un changement radical de mode de vie. Timothy Ferriss vous démontre, exemples concrets à l'appui, qu'il est possible de diviser son temps de travail par quatre tout en augmentant ses revenus.",
        details: {
            ean: "9782744064173",
            isbn: "2744064170",
            contributeurs: "Timothy Ferriss (Auteur principal)",
            format: "Livre broché",
            nbPages: 384,
            editeur: "Pearson",
            collection: "Développement personnel",
            largeur: "15 cm",
            longueur: "23 cm",
            epaisseur: "2.5 cm",
            poids: "0.500 kg",
            impression: "Non",
            categories: "Livres, Développement personnel, Productivité"
        }
    },

    // ============================================================
    // THRILLERS
    // ============================================================
    {
        id: 25,
        title: "La Psy",
        author: "Freida McFadden",
        price: 600,
        category: "thriller",
        image: "images/books/la-psy.jpg",
        isNew: true,
        isBestseller: false,
        description: "Tricia et Ethan piégés.",
        resume: "Jeunes mariés, Tricia et Ethan recherchent la maison de leurs rêves. Alors qu'ils visitent un manoir isolé ayant appartenu au docteur Adrienne Hale, une psychiatre renommée disparue sans laisser de trace quatre ans plus tôt, une violente tempête de neige les piège sur place. Un thriller psychologique haletant.",
        details: {
            ean: "9782290395677",
            isbn: "2290395676",
            contributeurs: "Freida McFadden (Auteur principal)",
            format: "Livre poche",
            nbPages: 416,
            editeur: "J'ai lu",
            collection: "J'ai lu Thriller",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.6 cm",
            poids: "0.220 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Thriller psychologique"
        }
    },
    {
        id: 26,
        title: "La Conversion",
        author: "James Baldwin",
        price: 500,
        category: "thriller",
        image: "images/books/la-conversion.jpg",
        isNew: true,
        isBestseller: false,
        description: "John Grimes.",
        resume: "Dans ce premier roman écrit en 1952, James Baldwin raconte l'histoire de John Grimes, un adolescent intelligent dans le Harlem des années 1930, et sa relation avec sa famille et son église. Un roman semi-autobiographique sur la religion, la race et l'identité.",
        details: {
            ean: "9782267045237",
            isbn: "2267045238",
            contributeurs: "James Baldwin (Auteur principal)",
            format: "Livre poche",
            nbPages: 288,
            editeur: "Christian Bourgois",
            collection: "Littérature étrangère",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.200 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Littérature américaine"
        }
    },
    {
        id: 27,
        title: "Le Joueur d'échecs",
        author: "Stefan Zweig",
        price: 300,
        category: "thriller",
        image: "images/books/le-joueur-dechecs.jpg",
        isNew: true,
        isBestseller: true,
        description: "Czentovic.",
        resume: "Prisonnier des nazis, Monsieur B., en dérobant un manuel d'échecs, a pu, à travers ce qui est devenu littéralement une folle passion, découvrir le moyen de résister à l'oppression. Cette dénonciation poignante de la barbarie nazie est le dernier texte écrit par Stefan Zweig avant son suicide.",
        details: {
            ean: "9782253075868",
            isbn: "2253075865",
            contributeurs: "Stefan Zweig (Auteur principal)",
            format: "Livre poche",
            nbPages: 96,
            editeur: "Le Livre de Poche",
            collection: "Le Livre de Poche",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "0.8 cm",
            poids: "0.100 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Classique"
        }
    },
    {
        id: 28,
        title: "Les P'tites Poules",
        author: "Christian Jolibois",
        price: 350,
        category: "thriller",
        image: "images/books/ptites-poules.jpg",
        isNew: true,
        isBestseller: false,
        description: "Carmen et Carmélito.",
        resume: "Au poulailler souffle un vent de folie. Carmen, Carmélito, Bélino et tous leurs copains ont la tête à l'envers. La fête des fous, c'est aujourd'hui ! Et les P'tites Poules n'ont plus qu'une idée : gagner l'épreuve la plus zinzin, la plus foldingue, et devenir pour un jour le roi des fous.",
        details: {
            ean: "9782226391377",
            isbn: "2226391372",
            contributeurs: "Christian Jolibois (Auteur principal)",
            format: "Livre poche",
            nbPages: 48,
            editeur: "Pocket Jeunesse",
            collection: "Pocket Jeunesse",
            largeur: "14 cm",
            longueur: "19 cm",
            epaisseur: "0.5 cm",
            poids: "0.100 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },

    // ============================================================
    // POÉSIE
    // ============================================================
    {
        id: 29,
        title: "Le Petit Prince",
        author: "Antoine de Saint-Exupéry",
        price: 500,
        category: "roman",
        image: "images/books/le-petit-prince.jpg",
        isNew: true,
        isBestseller: true,
        description: "Conte philosophique.",
        resume: "Le Petit Prince est une œuvre poétique et philosophique sous l'apparence d'un conte pour enfants. Le narrateur, un aviateur, rencontre un petit prince venu d'une autre planète. À travers leurs échanges, Saint-Exupéry aborde des thèmes universels comme l'amitié, l'amour, la solitude et le sens de la vie.",
        details: {
            ean: "9782070612758",
            isbn: "207061275X",
            contributeurs: "Antoine de Saint-Exupéry (Auteur principal)",
            format: "Livre poche",
            nbPages: 96,
            editeur: "Gallimard",
            collection: "Folio",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "0.8 cm",
            poids: "0.080 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Classique"
        }
    },
    {
        id: 30,
        title: "Une saison en enfer",
        author: "Arthur Rimbaud",
        price: 500,
        category: "poesie",
        image: "images/books/saison-enfer.jpg",
        isNew: true,
        isBestseller: false,
        description: "Poésie en prose.",
        resume: "Une saison en enfer est un recueil de poèmes en prose dans lequel le locuteur vit et affronte ce qu'il nomme l'enfer, entre existence réelle et visions. Une œuvre majeure de la poésie française qui a marqué le symbolisme et la littérature moderne.",
        details: {
            ean: "9782070365135",
            isbn: "2070365132",
            contributeurs: "Arthur Rimbaud (Auteur principal)",
            format: "Livre poche",
            nbPages: 128,
            editeur: "Gallimard",
            collection: "Poésie",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "0.8 cm",
            poids: "0.100 kg",
            impression: "Non",
            categories: "Livres, Poésie, Classique"
        }
    },
    {
        id: 31,
        title: "Capitale de la douleur",
        author: "Paul Éluard",
        price: 500,
        category: "poesie",
        image: "images/books/capitale-douleur.jpg",
        isNew: true,
        isBestseller: false,
        description: "Surréalisme.",
        resume: "Capitale de la douleur est le premier recueil surréaliste de Paul Éluard, poète incontournable du XXe siècle. Ce recueil comprend une centaine de poèmes, dont les deux tiers avaient déjà été publiés dans des revues. Une œuvre fondatrice du mouvement surréaliste.",
        details: {
            ean: "9782070300730",
            isbn: "2070300731",
            contributeurs: "Paul Éluard (Auteur principal)",
            format: "Livre poche",
            nbPages: 160,
            editeur: "Gallimard",
            collection: "Poésie",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1 cm",
            poids: "0.120 kg",
            impression: "Non",
            categories: "Livres, Poésie, Surréalisme"
        }
    },
    {
        id: 32,
        title: "Le Prophète",
        author: "Khalil Gibran",
        price: 500,
        category: "poesie",
        image: "images/books/prophete.jpg",
        isNew: true,
        isBestseller: false,
        description: "Amour, travail, liberté.",
        resume: "Après douze ans d'exil, son navire est enfin arrivé. La mer l'appelle. Bientôt, Almustafa va quitter la terre d'Orphalese. Avant de partir, il livre à la foule venue l'écouter des leçons de vie sur l'amour, le travail, la liberté, la mort. Une œuvre poétique universelle traduite en plus de 40 langues.",
        details: {
            ean: "9782253064091",
            isbn: "225306409X",
            contributeurs: "Khalil Gibran (Auteur principal)",
            format: "Livre poche",
            nbPages: 126,
            editeur: "Le Livre de Poche",
            collection: "Le Livre de Poche",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1 cm",
            poids: "0.100 kg",
            impression: "Non",
            categories: "Livres, Poésie, Philosophie"
        }
    },
    {
        id: 33,
        title: "Les Fleurs du Mal",
        author: "Charles Baudelaire",
        price: 500,
        category: "poesie",
        image: "images/books/les-fleurs-du-mal.jpg",
        isNew: true,
        isBestseller: true,
        description: "Symbolisme.",
        resume: "Les Fleurs du Mal est un recueil de poèmes de Charles Baudelaire qui a marqué l'histoire de la littérature française. L'œuvre explore les thèmes du mal, de la beauté, de la mort et de la mélancolie dans une langue d'une grande richesse et modernité.",
        details: {
            ean: "9782253056508",
            isbn: "225305650X",
            contributeurs: "Charles Baudelaire (Auteur principal)",
            format: "Livre poche",
            nbPages: 384,
            editeur: "Le Livre de Poche",
            collection: "Le Livre de Poche",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.200 kg",
            impression: "Non",
            categories: "Livres, Poésie, Classique"
        }
    },
    {
        id: 34,
        title: "Fureur et Mystère",
        author: "René Char",
        price: 500,
        category: "poesie",
        image: "images/books/fureur-mystere.jpg",
        isNew: true,
        isBestseller: false,
        description: "Résistance.",
        resume: "Fureur et Mystère est un recueil de poésie de René Char publié en 1948. Il rassemble ses textes poétiques écrits depuis près d'une décennie, de Seuls demeurent... Une œuvre majeure du poète résistant, marquée par son engagement et sa révolte contre l'oppression.",
        details: {
            ean: "9782070317962",
            isbn: "2070317960",
            contributeurs: "René Char (Auteur principal)",
            format: "Livre poche",
            nbPages: 224,
            editeur: "Gallimard",
            collection: "Poésie",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1 cm",
            poids: "0.150 kg",
            impression: "Non",
            categories: "Livres, Poésie, Résistance"
        }
    },

    // ============================================================
    // MANGAS (sélection)
    // ============================================================
    {
        id: 35,
        title: "One Piece – Tome 1",
        author: "Eiichiro Oda",
        price: 500,
        category: "manga",
        image: "images/books/one-piece-tome1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Luffy veut devenir Roi des Pirates.",
        resume: "Nous sommes à l'ère des pirates. Luffy, un garçon espiègle, rêve de devenir le roi des pirates en trouvant le 'One Piece', un fabuleux trésor. Il a avalé par mégarde un fruit démoniaque qui l'a transformé en homme-caoutchouc. Commence alors une grande aventure sur les mers.",
        details: {
            ean: "9782723480109",
            isbn: "2723480100",
            contributeurs: "Eiichiro Oda (Auteur principal)",
            format: "Livre poche",
            nbPages: 207,
            editeur: "Glénat",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.4 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 36,
        title: "Chainsaw Man – Tome 1",
        author: "Tatsuki Fujimoto",
        price: 600,
        category: "manga",
        image: "images/books/chainsaw-man-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Denji et son démon.",
        resume: "Pour rembourser ses dettes, Denji, jeune homme dans la dèche la plus totale, est exploité en tant que Devil Hunter avec son chien-démon-tronçonneuse, Pochita. Mais suite à une cruelle trahison, Denji se retrouve transformé en Chainsaw Man, un hybride mi-homme mi-démon, prêt à tout pour survivre.",
        details: {
            ean: "9782820338026",
            isbn: "2820338026",
            contributeurs: "Tatsuki Fujimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Kazé",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Seinen"
        }
    },
    {
        id: 37,
        title: "l'attaque des Titans – Tome 1",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren contre les Titans.",
        resume: "Dans un monde où l'humanité vit recluse derrière d'immenses murs pour se protéger des Titans, des créatures géantes dévoreuses d'hommes, Eren Yeager rêve de voir le monde extérieur. Après la destruction de son village, il jure de se venger et de libérer l'humanité.",
        details: {
            ean: "9782811620790",
            isbn: "2811620796",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 38,
        title: "Naruto – Tome 1",
        author: "Masashi Kishimoto",
        price: 500,
        category: "manga",
        image: "images/books/naruto-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Le ninja au démon-renard.",
        resume: "Konoha sévit Naruto, le pire garnement de l'école des ninjas ! Son passe-temps favori ? Faire des farces. Mais Naruto cache un terrible secret : il est le dépositaire du démon-renard à neuf queues qui a détruit le village. Déterminé à devenir Hokage, le chef de son village, il s'entraîne sans relâche.",
        details: {
            ean: "9782871296140",
            isbn: "2871296146",
            contributeurs: "Masashi Kishimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 187,
            editeur: "Kana",
            collection: "Shonen Kana",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.2 cm",
            poids: "0.160 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 39,
        title: "Dragon Ball – Tome 1",
        author: "Akira Toriyama",
        price: 500,
        category: "manga",
        image: "images/books/dragon-ball-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Son Goku et les Dragon Balls.",
        resume: "Son Goku, un jeune garçon avec une queue de singe, mène une vie paisible dans les montagnes jusqu'au jour où il rencontre Bulma, une jeune fille en quête des sept Dragon Balls. Si on les réunit, un dragon puissant apparaît et exauce un vœu. Commence alors une grande aventure.",
        details: {
            ean: "9782723480918",
            isbn: "2723480917",
            contributeurs: "Akira Toriyama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Glénat",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 40,
        title: "Demon Slayer – Tome 1",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Tanjiro sauve sa sœur.",
        resume: "Le Japon, au début du XXe siècle. Tanjiro, un jeune marchand de charbon, mène une vie paisible jusqu'au jour funeste où il découvre sa famille entièrement décimée par un démon. Sa sœur Nezuko est la seule survivante, mais elle a été transformée en démon. Tanjiro décide de devenir un pourfendeur de démons pour trouver un remède.",
        details: {
            ean: "9791039101264",
            isbn: "1039101268",
            contributeurs: "Koyoharu Gotouge (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 41,
        title: "Fruits Basket – Tome 1",
        author: "Natsuki Takaya",
        price: 500,
        category: "manga",
        image: "images/books/fruits-basket-1.jpg",
        isNew: true,
        isBestseller: false,
        description: "La malédiction du zodiaque.",
        resume: "Tohru Honda, jeune lycéenne courageuse et volontaire, vit sous une tente dans les bois depuis que sa mère est décédée. Elle est découverte par la famille Soma, qui l'invite à vivre chez eux. Mais Tohru découvre bientôt que les Soma sont maudits : ils se transforment en animaux du zodiaque chinois lorsqu'ils sont stressés ou serrés dans les bras.",
        details: {
            ean: "9782344040830",
            isbn: "2344040831",
            contributeurs: "Natsuki Takaya (Auteur principal)",
            format: "Livre poche",
            nbPages: 200,
            editeur: "Akata",
            collection: "Shojo",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shojo"
        }
    },
    {
        id: 42,
        title: "Sailor Moon – Tome 1",
        author: "Naoko Takeuchi",
        price: 500,
        category: "manga",
        image: "images/books/sailor-moon-1.jpg",
        isNew: true,
        isBestseller: false,
        description: "Usagi, guerrière magique.",
        resume: "Usagi Tsukino est une jeune collégienne un peu maladroite et pleurnicharde. Sa vie change lorsqu'elle rencontre un chat noir qui lui apprend qu'elle est la réincarnation d'une guerrière lunaire, Sailor Moon. Elle doit désormais protéger la Terre des forces du mal.",
        details: {
            ean: "9782723485647",
            isbn: "2723485641",
            contributeurs: "Naoko Takeuchi (Auteur principal)",
            format: "Livre poche",
            nbPages: 226,
            editeur: "Glénat",
            collection: "Shojo",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.4 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shojo"
        }
    },
    {
        id: 43,
        title: "Jujutsu Kaisen – Tome 1",
        author: "Gege Akutami",
        price: 500,
        category: "manga",
        image: "images/books/jujutsu-kaisen-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Yuji et Sukuna.",
        resume: "Yuji Itadori est un lycéen au physique hors norme qui intègre le club de recherche sur les phénomènes occultes. Un jour, il tombe sur un doigt maudit qui attire les démons. Pour sauver ses amis, il avale le doigt et devient l'hôte de Ryomen Sukuna, un démon redoutable.",
        details: {
            ean: "9791032706749",
            isbn: "1032706740",
            contributeurs: "Gege Akutami (Auteur principal)",
            format: "Livre poche",
            nbPages: 188,
            editeur: "Ki-oon",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 44,
        title: "Vinland Saga – Tome 1",
        author: "Makoto Yukimura",
        price: 550,
        category: "manga",
        image: "images/books/vinland-saga-1.jpg",
        isNew: true,
        isBestseller: false,
        description: "Thorfinn, vengeance et paix.",
        resume: "Thorfinn est un jeune guerrier viking qui a juré de venger la mort de son père, tué par le chef de guerre Askeladd. Pour cela, il s'est engagé dans sa troupe et participe à ses pillages. Mais peu à peu, Thorfinn remet en question sa quête de vengeance et aspire à un monde de paix.",
        details: {
            ean: "9782351423554",
            isbn: "2351423550",
            contributeurs: "Makoto Yukimura (Auteur principal)",
            format: "Livre poche",
            nbPages: 213,
            editeur: "Kurokawa",
            collection: "Seinen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.4 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Mangas, Seinen"
        }
    },

    // ============================================================
    // NOUVEAUX LIVRES
    // ============================================================
    {
        id: 45,
        title: "Hunger Games",
        author: "Suzanne Collins",
        price: 500,
        category: "roman",
        image: "images/books/hunger-games.jpg",
        isNew: true,
        isBestseller: true,
        description: "Katniss et les jeux de la faim.",
        resume: "Dans un futur sombre, sur les ruines des États-Unis, un jeu télévisé est organisé chaque année. Vingt-quatre jeunes, un garçon et une fille par district, sont tirés au sort pour participer aux Hunger Games. La règle est simple : 24 concurrents, un seul survivant. Katniss Everdeen se porte volontaire pour sauver sa sœur.",
        details: {
            ean: "9782266228030",
            isbn: "2266228038",
            contributeurs: "Suzanne Collins (Auteur principal), Guillaume Fournier (Traducteur)",
            format: "Livre poche",
            nbPages: 432,
            editeur: "Pocket Jeunesse",
            collection: "Pocket Jeunesse",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.8 cm",
            poids: "0.250 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Science-fiction"
        }
    },
    {
        id: 46,
        title: "Matilda",
        author: "Roald Dahl",
        price: 400,
        category: "roman",
        image: "images/books/matilda.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une petite fille surdouée.",
        resume: "Matilda est une petite fille surdouée de cinq ans qui adore lire. Ses parents, qui la négligent, ne comprennent pas son intelligence exceptionnelle. À l'école, elle affronte la terrible directrice Miss Trunchbull et découvre qu'elle possède des pouvoirs télékinésiques.",
        details: {
            ean: "9782070618361",
            isbn: "2070618367",
            contributeurs: "Roald Dahl (Auteur principal)",
            format: "Livre poche",
            nbPages: 272,
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.5 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.200 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Roman"
        }
    },
    {
        id: 47,
        title: "Le Petit Nicolas",
        author: "René Goscinny",
        price: 350,
        category: "roman",
        image: "images/books/le-petit-nicolas.jpg",
        isNew: true,
        isBestseller: false,
        description: "Les aventures de Nicolas.",
        resume: "Le Petit Nicolas est une série de livres pour enfants créée par René Goscinny et illustrée par Sempé. Les histoires racontent les aventures d'un petit garçon, Nicolas, et de sa bande de copains à l'école et à la maison.",
        details: {
            ean: "9782070616503",
            isbn: "207061650X",
            contributeurs: "René Goscinny (Auteur principal), Sempé (Illustrateur)",
            format: "Livre poche",
            nbPages: 160,
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.5 cm",
            longueur: "18 cm",
            epaisseur: "1 cm",
            poids: "0.150 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Roman"
        }
    },
    {
        id: 48,
        title: "Tous nos lendemains",
        author: "lylyblabla",
        price: 850,
        category: "roman",
        image: "images/books/tous-nos-lendemains.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un roman contemporain.",
        resume: "Chris et Chloé s’adorent autant qu’ils s’exaspèrent. Plus de trois minutes dans la même pièce et c’est l’apocalypse. Et pour cause : Chloé n’a jamais pardonné à Chris... Une romance poignante marquée par la maladie, l’espoir et la force des sentiments.",
        details: {
            ean: "9782755698534",
            isbn: "2755698531",
            contributeurs: "Lyly Blabla (Auteur principal)",
            format: "Livre poche",
            nbPages: 496,
            editeur: "Hugo & Cie",
            collection: "Romance",
            largeur: "14 cm",
            longueur: "21 cm",
            epaisseur: "2.5 cm",
            poids: "0.450 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Romance"
        }
    },
    {
        id: 49,
        title: "Âmes miroirs",
        author: "Olivia Atwater",
        price: 600,
        category: "jeunesse",
        image: "images/books/ames-miroirs.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un roman fantastique.",
        resume: "Dans un roman aux airs du Château Ambulant de Miyazaki, découvrez la fabuleuse relation entre Theodora, une jeune fille, et le monde des faës. Un roman historique qui mêle enquête et magie, le tout saupoudré d'une pointe de romance.",
        details: {
            ean: "9782226484345",
            isbn: "2226484346",
            contributeurs: "Olivia Atwater (Auteur principal), Nathalie Huet (Traducteur)",
            format: "Livre broché",
            nbPages: 360,
            editeur: "Albin Michel Jeunesse",
            collection: "Fantasy",
            largeur: "14 cm",
            longueur: "21 cm",
            epaisseur: "2.2 cm",
            poids: "0.400 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Fantasy"
        }
    },

    // ============================================================
    // MANGAS SUPPLÉMENTAIRES
    // ============================================================
    {
        id: 50,
        title: "One Piece – Tome 8",
        author: "Eiichiro Oda",
        price: 500,
        category: "manga",
        image: "images/books/one-piece-8.jpg",
        isNew: true,
        isBestseller: true,
        description: "Luffy et son équipage.",
        resume: "Suite et fin du combat dantesque entre Luffy et le capitaine Creek. Fidèle à ses convictions et ignorant la peur, Luffy défie Don Krieg sans la moindre hésitation afin de mettre fin à la bataille acharnée qui fait rage sur le Baratie.",
        details: {
            ean: "9782723485838",
            isbn: "2723485830",
            contributeurs: "Eiichiro Oda (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Glénat",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 51,
        title: "One Punch Man – Tome 1",
        author: "Yusuke Murata",
        price: 500,
        category: "manga",
        image: "images/books/one-punch-man-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Saitama, le héros le plus puissant.",
        resume: "Saitama est un jeune homme sans emploi et sans réelle perspective d'avenir, jusqu'au jour où il décide de prendre sa vie en main. Son nouvel objectif : devenir un super-héros. Après un entraînement intensif, il est devenu si puissant qu'il peut vaincre n'importe quel ennemi en un seul coup de poing.",
        details: {
            ean: "9782368523263",
            isbn: "2368523269",
            contributeurs: "Yusuke Murata (Illustrateur), ONE (Scénariste)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Kurokawa",
            collection: "Seinen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Seinen"
        }
    },
    {
        id: 52,
        title: "Demon Slayer – Tome 9",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-9.jpg",
        isNew: true,
        isBestseller: true,
        description: "Tanjiro affronte les démons.",
        resume: "Tanjiro, Zenitsu et Inosuke sont partis en mission dans le quartier des plaisirs de Yoshiwara avec Tengen Uzui, le pilier du son. En effet, c'est là-bas que les trois kunoichis de Tengen, envoyées en reconnaissance pour débusquer un démon, ont disparu. Pour mener leur enquête, ils doivent se déguiser en filles.",
        details: {
            ean: "9791039124775",
            isbn: "1039124772",
            contributeurs: "Koyoharu Gotouge (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 53,
        title: "Demon Slayer – Tome 12",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-12.jpg",
        isNew: true,
        isBestseller: true,
        description: "Suite des aventures.",
        resume: "Pour la première fois depuis 113 ans, un démon de la lune supérieure a été battu. Hors de lui, Muzan convoque les autres démons de la lune supérieure afin de leur ordonner d'intensifier l'attaque contre les pourfendeurs. Lors de la bataille contre Dahi et Gyutaro, le sabre de Tanjiro a été brisé.",
        details: {
            ean: "9791039115643",
            isbn: "1039115641",
            contributeurs: "Koyoharu Gotouge (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 54,
        title: "Demon Slayer – Tome 13",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-13.jpg",
        isNew: true,
        isBestseller: true,
        description: "Suite des aventures.",
        resume: "Les lunes supérieures Gyokko et Hantengu ont attaqué le village caché des forgeurs de sabres. Tandis que Tanjiro, Genya et Nezuko font face à Hantengu (qui se dédouble à chaque fois qu'on lui coupe un membre), Tokito, le pilier de la Brume, et Kanroji, le pilier de l'Amour, affrontent Gyokko.",
        details: {
            ean: "9791039115650",
            isbn: "103911565X",
            contributeurs: "Koyoharu Gotouge (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 55,
        title: "Demon Slayer – Tome 14",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-14.jpg",
        isNew: true,
        isBestseller: true,
        description: "Suite des aventures.",
        resume: "A peine Tanjiro et Genya croient-ils avoir vaincu la lune supérieure Hantengu que celui-ci créé un avatar encore plus puissant : Zohakuten, la personnification de la Haine. Les avatars de la quatrième lune supérieure ont fusionné pour attaquer Tanjiro, qui doit alors mener un combat difficile.",
        details: {
            ean: "9791039115667",
            isbn: "1039115668",
            contributeurs: "Koyoharu Gotouge (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 56,
        title: "l'attaque des Titans – Tome 10",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-10.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren et les Titans.",
        resume: "Avec la brèche dans le mur Rose, le 104e bataillon doit évacuer les villages menacés par les Titans. Sur le chemin de la sécurité, ils décident de passer la nuit au château d'Utgard. Mais l'ennemi est déjà là...",
        details: {
            ean: "9782811625429",
            isbn: "2811625429",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 57,
        title: "l'attaque des Titans – Tome 13",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-13.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren et les Titans.",
        resume: "Erwin est parvenu à récupérer Eren des mains des Titans. Mais pendant la bataille, il a fait une découverte qui pourrait changer le cours de l'histoire. Le gouvernement royal n'est plus digne de diriger l'humanité...",
        details: {
            ean: "9782811625467",
            isbn: "2811625461",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 58,
        title: "l'attaque des Titans – Tome 14",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-14.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren et les Titans.",
        resume: "Le gouvernement royal, qui a placé sa propre richesse et sa position au-dessus de la survie de l'humanité, n'est plus digne de diriger. Erwin a pris une décision cruciale : renverser le pouvoir en place.",
        details: {
            ean: "9782811625474",
            isbn: "281162547X",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 59,
        title: "l'attaque des Titans – Tome 15",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-15.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren et les Titans.",
        resume: "L'interrogatoire d'un membre de la police militaire a révélé que Krista (alias Historia Reiss) est la véritable héritière du trône. Le combat pour le pouvoir s'intensifie dans les murs.",
        details: {
            ean: "9782811625481",
            isbn: "2811625488",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 60,
        title: "Hunter x Hunter – Tome 5",
        author: "Yoshihiro Togashi",
        price: 500,
        category: "manga",
        image: "images/books/hunter-x-hunter-5.jpg",
        isNew: true,
        isBestseller: true,
        description: "Gon et ses amis.",
        resume: "Dans les pas de son père, Gon quitte son village pour se présenter au difficile examen des Hunters. En chemin, Gon se fera des amis et devra affronter des participants particulièrement dangereux. L'examen Hunter est une épreuve de tous les dangers.",
        details: {
            ean: "9782871292470",
            isbn: "2871292477",
            contributeurs: "Yoshihiro Togashi (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Kana",
            collection: "Shonen Kana",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 61,
        title: "Hunter x Hunter – Tome 7",
        author: "Yoshihiro Togashi",
        price: 500,
        category: "manga",
        image: "images/books/hunter-x-hunter-7.jpg",
        isNew: true,
        isBestseller: true,
        description: "Gon et ses amis.",
        resume: "Fin de l'interdiction d'utiliser le 'nen' ! Promesse tenue pendant 2 mois ! Le véritable entraînement peut commencer. Ce septième volume est celui où Hunter x Hunter prend une dimension nouvelle avec l'introduction concrète du Nen, ce système de pouvoir qui va devenir central.",
        details: {
            ean: "9782871292487",
            isbn: "2871292485",
            contributeurs: "Yoshihiro Togashi (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Kana",
            collection: "Shonen Kana",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 62,
        title: "Naruto – Tome 10",
        author: "Masashi Kishimoto",
        price: 500,
        category: "manga",
        image: "images/books/naruto-10.jpg",
        isNew: true,
        isBestseller: true,
        description: "Naruto et ses compagnons.",
        resume: "Vingt candidats s'affrontent dans des duels au sommet afin de pouvoir participer à la troisième épreuve de l'examen chunin. Lee affronte le redoutable Gaara dans un combat qui va marquer les esprits.",
        details: {
            ean: "9782871296140",
            isbn: "2871296146",
            contributeurs: "Masashi Kishimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 187,
            editeur: "Kana",
            collection: "Shonen Kana",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.2 cm",
            poids: "0.160 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 63,
        title: "Naruto – Tome 11",
        author: "Masashi Kishimoto",
        price: 500,
        category: "manga",
        image: "images/books/naruto-11.jpg",
        isNew: true,
        isBestseller: true,
        description: "Naruto et ses compagnons.",
        resume: "Naruto s'entraîne avec un nouveau mentor, Jiraiya, pour maîtriser le chakra du démon-renard à neuf queues enfermé en lui. Pendant ce temps, les épreuves de l'examen chunin continuent, et les ennemis se font de plus en plus dangereux.",
        details: {
            ean: "9782871297925",
            isbn: "2871297924",
            contributeurs: "Masashi Kishimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 187,
            editeur: "Kana",
            collection: "Shonen Kana",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.2 cm",
            poids: "0.160 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 64,
        title: "Blue Lock – Tome 1",
        author: "Muneyuki Kaneshiro",
        price: 500,
        category: "manga",
        image: "images/books/blue-lock-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Le football version survival.",
        resume: "L'objectif du coach du Blue Lock, Jinpachi Ego, est clair : détecter l'unique attaquant qui écrasera tous ses rivaux par son talent et son hyper-individualisme. Pour Yoichi Isagi, c'est l'occasion de devenir le meilleur buteur du monde.",
        details: {
            ean: "9782811671277",
            isbn: "2811671277",
            contributeurs: "Muneyuki Kaneshiro (Auteur principal), Yusuke Nomura (Illustrateur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 65,
        title: "Blue Lock – Tome 2",
        author: "Muneyuki Kaneshiro",
        price: 500,
        category: "manga",
        image: "images/books/blue-lock-2.jpg",
        isNew: true,
        isBestseller: true,
        description: "Le football version survival.",
        resume: "Ayant survécu au premier écrémage, Yoichi Isagi se retrouve dans l'équipe Z, formée exclusivement d'attaquants. Avec elle, il devra lutter dans une poule de cinq équipes où seules les deux meilleures resteront en lice.",
        details: {
            ean: "9782811671284",
            isbn: "2811671285",
            contributeurs: "Muneyuki Kaneshiro (Auteur principal), Yusuke Nomura (Illustrateur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 66,
        title: "Chainsaw Man – Tome 7",
        author: "Tatsuki Fujimoto",
        price: 500,
        category: "manga",
        image: "images/books/chainsaw-man-7.jpg",
        isNew: true,
        isBestseller: true,
        description: "Denji et ses démons.",
        resume: "La bataille fait rage entre la team de Quanxi et la section spéciale. Le mystérieux Père Noël dévoile l'étendue de son pouvoir et, par là-même, son véritable objectif. Un contrat maudit chargé de haine et taché de sang se lie, ouvrant la porte vers un monde de désespoir.",
        details: {
            ean: "9782820347264",
            isbn: "2820347262",
            contributeurs: "Tatsuki Fujimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Kazé",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 67,
        title: "Chainsaw Man – Tome 8",
        author: "Tatsuki Fujimoto",
        price: 500,
        category: "manga",
        image: "images/books/chainsaw-man-8.jpg",
        isNew: true,
        isBestseller: true,
        description: "Denji et ses démons.",
        resume: "Un contrat maudit chargé de haine et taché de sang se lie, ouvrant la porte vers un monde de désespoir que même les démons redoutent. Entre effroi et désolation, les voici transportés dans le domaine du démon-ténèbres.",
        details: {
            ean: "9782820349008",
            isbn: "2820349001",
            contributeurs: "Tatsuki Fujimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Kazé",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },

    // ============================================================
    // LIVRES JEUNESSE / ALBUMS
    // ============================================================
    {
        id: 68,
        title: "Je t'aimerai toujours, quoi qu'il arrive...",
        author: "Debi Gliori",
        price: 500,
        category: "jeunesse",
        image: "images/books/je-taimerai-toujours.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un album tendre sur l'amour inconditionnel.",
        resume: "Petit Renard est de très mauvaise humeur. Il dit que personne ne l'aime. Mais sa maman va lui expliquer que leur amour durera toujours, quoi qu'il arrive. Une histoire tendre sur l'amour maternel et la confiance.",
        details: {
            ean: "9782013933995",
            isbn: "2013933996",
            contributeurs: "Debi Gliori (Auteur principal)",
            format: "Livre broché",
            nbPages: 32,
            editeur: "Gautier Languereau",
            collection: "Les petites histoires du soir",
            largeur: "20.3 cm",
            longueur: "23.6 cm",
            epaisseur: "0.8 cm",
            poids: "0.300 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },
    {
        id: 69,
        title: "Le monstre des couleurs : la couleur des émotions",
        author: "Anna Llenas",
        price: 1500,
        category: "jeunesse",
        image: "images/books/le-monstre-des-couleurs.jpg",
        isNew: true,
        isBestseller: true,
        description: "Un livre animé pour aider les enfants à identifier leurs émotions.",
        resume: "Le monstre des couleurs se sent tout barbouillé, aujourd'hui. Ses émotions sont sens dessus dessous ! Il ne comprend pas ce qui lui arrive. Un album illustré pour découvrir ses émotions et apprendre à les identifier.",
        details: {
            ean: "9782508036530",
            isbn: "2508036534",
            contributeurs: "Anna Llenas (Auteur principal)",
            format: "Livre animé",
            nbPages: 48,
            editeur: "Glénat Jeunesse",
            collection: "Les émotions",
            largeur: "25.2 cm",
            longueur: "25.2 cm",
            epaisseur: "2.5 cm",
            poids: "0.600 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },
    {
        id: 70,
        title: "Grosse Colère",
        author: "Mireille d'Allancé",
        price: 500,
        category: "jeunesse",
        image: "images/books/grosse-colere.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une histoire sur la colère et comment l'apprivoiser.",
        resume: "Robert a passé une très mauvaise journée. Il n'est pas de bonne humeur et en plus, son papa l'a envoyé dans sa chambre. Alors Robert sent tout à coup une grosse colère monter en lui. Un album qui traite avec justesse le thème de la colère chez l'enfant.",
        details: {
            ean: "9782211231134",
            isbn: "2211231139",
            contributeurs: "Mireille d'Allancé (Auteur principal)",
            format: "Livre poche",
            nbPages: 32,
            editeur: "L'École des Loisirs",
            collection: "Lutin poche",
            largeur: "19 cm",
            longueur: "15 cm",
            epaisseur: "0.5 cm",
            poids: "0.100 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },
    {
        id: 71,
        title: "Au revoir Blaireau",
        author: "Susan Varley",
        price: 500,
        category: "jeunesse",
        image: "images/books/au-revoir-blaireau.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un album poignant sur le deuil et l'amitié.",
        resume: "Un matin, les amis de Blaireau se rassemblent devant sa porte. Ils s'inquiètent parce que leur vieil ami n'est pas venu pour leur dire bonjour comme d'habitude. Le vieux Blaireau va mourir, mais il existera toujours dans le cœur de ceux qui l'aiment, grâce aux souvenirs qu'il leur laisse.",
        details: {
            ean: "9782075136394",
            isbn: "2075136394",
            contributeurs: "Susan Varley (Auteur principal)",
            format: "Livre broché",
            nbPages: 32,
            editeur: "Gallimard Jeunesse",
            collection: "Album",
            largeur: "21 cm",
            longueur: "26 cm",
            epaisseur: "0.8 cm",
            poids: "0.350 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },
    {
        id: 72,
        title: "La boite à étoiles",
        author: "Jerome Camil",
        price: 1100,
        category: "jeunesse",
        image: "images/books/la-boite-a-etoiles.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une histoire poétique sur les rêves et l'imagination.",
        resume: "Un petit écureuil aimerait offrir une étoile à sa maman. Ce cadeau lui tient à cœur ! Pour lui dire au revoir. Pour donner un sens à la mort. Accompagné de son meilleur copain, un jeune écureuil se met en quête d'une étoile pour sa maman.",
        details: {
            ean: "9782874265413",
            isbn: "2874265418",
            contributeurs: "Jerome Camil (Auteur principal)",
            format: "Livre broché",
            nbPages: 32,
            editeur: "ALICE",
            collection: "Album",
            largeur: "22 cm",
            longueur: "28 cm",
            epaisseur: "0.8 cm",
            poids: "0.380 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },
    {
        id: 73,
        title: "Une surprise pour maman",
        author: "Karine-Marie Amiot, Diane De Saint-exupery",
        price: 850,
        category: "jeunesse",
        image: "images/books/une-surprise-pour-maman.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un album pour célébrer l'amour filial.",
        resume: "Avec des textes pleins de poésie de Karine-Marie Amiot et des illustrations délicates de Diane de Saint-Exupéry, cet album raconte, de façon tendre et joyeuse, les préparatifs de la Fête des mères. Une histoire poétique évoquant de manière tendre les préparatifs de la fête des mères.",
        details: {
            ean: "9782728933103",
            isbn: "2728933102",
            contributeurs: "Karine-Marie Amiot (Auteur principal), Diane De Saint-exupery (Illustrateur)",
            format: "Livre relié",
            nbPages: 32,
            editeur: "MAME",
            collection: "La famille Lapin",
            largeur: "21 cm",
            longueur: "26 cm",
            epaisseur: "0.8 cm",
            poids: "0.350 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },
    {
        id: 74,
        title: "Petit amour",
        author: "Nadine Brun-Cosme, Marion Cocklico",
        price: 800,
        category: "jeunesse",
        image: "images/books/petit-amour.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un livre tendre sur les premiers émois.",
        resume: "Une histoire tendre pour aider votre tout-petit à reconnaître ses émotions, et pour partager avec lui un moment de bonheur. Un livre cartonné pour les tout-petits sur le thème de l'amour.",
        details: {
            ean: "9782215138172",
            isbn: "2215138176",
            contributeurs: "Nadine Brun-Cosme (Auteur principal), Marion Cocklico (Illustrateur)",
            format: "Livre cartonné",
            nbPages: 12,
            editeur: "Fleurus",
            collection: "Petit doux",
            largeur: "18 cm",
            longueur: "18 cm",
            epaisseur: "1.2 cm",
            poids: "0.250 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },
    {
        id: 75,
        title: "Dans le magasin des mamans j'aurais choisi toi",
        author: "Mathou",
        price: 1100,
        category: "jeunesse",
        image: "images/books/dans-le-magasin-des-mamans.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un message d'amour pour sa maman.",
        resume: "Quand nos enfants posent leur regard malicieux et clairvoyant sur nos imperfections de parents... Une déclaration d'amour espiègle, drôle et totalement décomplexante. Un album humoristique dans lequel des enfants posent leur regard malicieux sur les imperfections de leurs parents.",
        details: {
            ean: "9782221265774",
            isbn: "2221265773",
            contributeurs: "Mathou (Auteur principal)",
            format: "Livre broché",
            nbPages: 32,
            editeur: "Robert Laffont",
            collection: "Album",
            largeur: "21.2 cm",
            longueur: "25.8 cm",
            epaisseur: "1.1 cm",
            poids: "0.400 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Album"
        }
    },
    {
        id: 76,
        title: "Les Schtroumpfs Tome 39 : Les Schtroumpfs et la tempête blanche",
        author: "Peyo, Alain Jost, Thierry Culliford",
        price: 1000,
        category: "bd",
        image: "images/books/schtroumpfs-tome39.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une aventure des Schtroumpfs dans la neige.",
        resume: "Comme chaque année, les premiers frimas sont attendus de pied ferme par les Schtroumpfs, qui se sont bien préparés. Mais personne ne s'attendait à un tel blizzard ! Partis tester une nouvelle luge, les Schtroumpfs Farceur, à Lunettes et Bricoleur se retrouvent coupés du village.",
        details: {
            ean: "9782803680047",
            isbn: "2803680041",
            contributeurs: "Peyo (Auteur principal), Alain Jost, Thierry Culliford",
            format: "Livre broché",
            nbPages: 48,
            editeur: "Le Lombard",
            collection: "Les Schtroumpfs",
            largeur: "21 cm",
            longueur: "29 cm",
            epaisseur: "0.8 cm",
            poids: "0.350 kg",
            impression: "Non",
            categories: "Livres, BD, Humour"
        }
    },
    {
        id: 77,
        title: "Pokémon - La grande aventure Tome 1",
        author: "Hidenori Kusaka, Mato",
        price: 800,
        category: "manga",
        image: "images/books/pokemon-grande-aventure-t1.jpg",
        isNew: true,
        isBestseller: false,
        description: "Les aventures de Pokémon en version manga.",
        resume: "Rouge est persuadé d'avoir déjoué pour de bon les plans de la Team Rocket avec l'aide de ses amis. Toujours décidé à compléter le pokédex que lui a confié le professeur Chen, il repart sur les routes accompagné de ses pokémons.",
        details: {
            ean: "9782368522518",
            isbn: "2368522513",
            contributeurs: "Hidenori Kusaka (Scénariste), Mato (Illustrateur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Kurokawa",
            collection: "Shonen",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.3 cm",
            poids: "0.170 kg",
            impression: "Non",
            categories: "Livres, Mangas, Shonen"
        }
    },
    {
        id: 78,
        title: "Les aventures de Tintin, le secret de la licorne",
        author: "Steven Spielberg (réalisateur)",
        price: 400,
        category: "bd",
        image: "images/books/tintin-secret-licorne.jpg",
        isNew: false,
        isBestseller: false,
        description: "Le film d'animation adapté de la BD d'Hergé.",
        resume: "Parce qu'il achète la maquette d'un bateau appelé la Licorne, le jeune reporter Tintin se retrouve entraîné dans une fantastique aventure à la recherche d'un fabuleux secret. Avec l'aide de Milou, il va devoir percer le mystère de la Licorne.",
        details: {
            ean: "9781480603303",
            isbn: "1480603301",
            contributeurs: "Steven Spielberg (Réalisateur), Hergé (Auteur adapté)",
            format: "DVD",
            nbPages: 1,
            editeur: "Sony Pictures Home Entertainment",
            collection: "Film",
            largeur: "13.5 cm",
            longueur: "19 cm",
            epaisseur: "1.5 cm",
            poids: "0.100 kg",
            impression: "Non",
            categories: "Livres, BD, Film"
        }
    }
];
