// js/books-data.js - DONNÉES COMPLÈTES DES LIVRES MAURILIVRES

const booksData = [
    // ============================================================
    // ROMANS (1 à 16)
    // ============================================================
    {
        id: 1,
        title: "L'Enfant noir",
        author: "Camara Laye",
        price: 400,
        category: "roman",
        image: "images/books/camara-laye.jpg",
        isNew: true,
        isBestseller: true,
        description: "Autobiographie d'une enfance en Haute-Guinée.",
        resume: "LES GRANDS TEXTES DU XXe SIÈCLE L'enfant noir grandit dans un village de Haute-Guinée où le merveilleux côtoie quotidiennement la réalité. Son père, forgeron, travaille l'or au rythme de la harpe des griots et des incantations aux génies du feu et du vent. Respectée de tous, sa mère jouit de mystérieux pouvoirs sur les êtres et les choses. Elle sait détourner les sortilèges et tenir à l'écart les crocodiles du fleuve Niger. Aîné de la famille, le petit garçon est destiné à prendre la relève de son père à l'atelier et, surtout, à perpétuer l'esprit de sa caste au sein du village. Mais son puissant désir d'apprendre l'entraînera inéluctablement vers d'autres horizons, loin des traditions et des coutumes de son peuple. Un livre intemporel qui s'est imposé comme un classique de notre temps.",
        details: {
            ean: "9782266178945",
            isbn: "2266178946",
            contributeurs: "Camara Laye (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pocket",
            collection: "Best",
            largeur: "10.9 cm",
            longueur: "17.8 cm",
            epaisseur: "1.4 cm",
            poids: "0.129 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Littérature francophone"
        }
    },
    {
        id: 2,
        title: "Marche ou crève",
        author: "Stephen King",
        price: 600,
        category: "roman",
        image: "images/books/marche-ou-creve.jpg",
        isNew: true,
        isBestseller: false,
        description: "Cent adolescents en marche forcée.",
        resume: "Garraty, un jeune adolescent natif du Maine, va concourir pour « La Longue Marche », une compétition qui compte cent participants. La règle est simple : marcher sans jamais s'arrêter. Celui qui ralentit ou s'arrête est éliminé... définitivement. Une course contre la montre haletante où chaque pas peut être le dernier.",
        details: {
            ean: "9782290308370",
            isbn: "2290308374",
            contributeurs: "Stephen King (Auteur principal)",
            format: "Livre poche",
            nbPages: 400,
            editeur: "J'ai lu",
            collection: "Thriller",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.8 cm",
            poids: "0.220 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Thriller"
        }
    },
    {
        id: 3,
        title: "Priére aux vivants pour leur pardonner d'être vivants",
        author: "Charlotte Delbo",
        price: 500,
        category: "roman",
        image: "images/books/charlotte.jpg",
        isNew: false,
        isBestseller: true,
        description: "Vie tragique de Charlotte Salomon.",
        resume: "Charlotte Salomon, artiste peintre morte à vingt-six ans alors qu'elle était enceinte. Après une enfance à Berlin marquée par une tragédie familiale, Charlotte est exclue progressivement par les nazis de toutes les sphères de la société allemande. Un roman poignant sur la vie d'une artiste juive pendant la Seconde Guerre mondiale.",
        details: {
            ean: "9782070458356",
            isbn: "2070458351",
            contributeurs: "David Foenkinos (Auteur principal)",
            format: "Livre poche",
            nbPages: 256,
            editeur: "Gallimard",
            collection: "Folio",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.150 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Littérature française"
        }
    },
    {
        id: 4,
        title: "La Femme de ménage",
        author: "Freida McFadden",
        price: 600,
        category: "roman",
        image: "images/books/femme-menage.jpg",
        isNew: true,
        isBestseller: true,
        description: "Millie découvre des secrets sombres.",
        resume: "Chaque jour, Millie fait le ménage dans la belle maison des Winchester, une riche famille new-yorkaise. Elle récupère aussi leur fille à l'école et prépare les repas. Mais Millie découvre peu à peu des secrets sombres qui se cachent derrière les murs de cette maison. Un thriller psychologique captivant.",
        details: {
            ean: "9782290391174",
            isbn: "2290391174",
            contributeurs: "Freida McFadden (Auteur principal)",
            format: "Livre poche",
            nbPages: 416,
            editeur: "J'ai lu",
            collection: "Thriller",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.6 cm",
            poids: "0.210 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Thriller psychologique"
        }
    },
    {
        id: 5,
        title: "Nos étoiles contraires",
        author: "John Green",
        price: 600,
        category: "roman",
        image: "images/books/nos-etoiles-contraires.jpg",
        isNew: true,
        isBestseller: true,
        description: "Hazel et Augustus.",
        resume: "Hazel, 16 ans, est atteinte d'un cancer. Son dernier traitement semble avoir arrêté l'évolution de la maladie, mais elle se sait condamnée. Elle rencontre Augustus, un jeune homme atteint d'un cancer également, et une histoire d'amour bouleversante naît entre eux. Un roman poignant sur la vie, la mort et l'amour.",
        details: {
            ean: "9782092552300",
            isbn: "2092552307",
            contributeurs: "John Green (Auteur principal), Catherine Gibert (Traducteur)",
            format: "Livre poche",
            nbPages: 330,
            editeur: "Nathan",
            collection: "Littérature jeunesse",
            largeur: "14 cm",
            longueur: "21 cm",
            epaisseur: "1.8 cm",
            poids: "0.320 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Roman jeunesse"
        }
    },
    {
        id: 6,
        title: "Mille et un je",
        author: "Mariam Derwich",
        price: 300,
        category: "poésie",
        image: "images/books/mille-en-un.jpg",
        isNew: true,
        isBestseller: false,
        description: "Recueil de poésie.",
        resume: "Métisse de père mauritanien et de mère française, Marième Mint Derwich dit rêver d'une Mauritanie arc-en-ciel. Son recueil 'Mille et un Je' est une invitation à la réflexion sur l'identité, le métissage et la condition de la femme mauritanienne.",
        details: {
            ean: "9782343152105",
            isbn: "2343152109",
            contributeurs: "Mariam Derwich (Auteur principal)",
            format: "Livre broché",
            nbPages: 120,
            editeur: "Editions de la Librairie 15/21",
            collection: "Lettres Mauritaniennes",
            largeur: "13.5 cm",
            longueur: "21.5 cm",
            epaisseur: "1 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Poésie, Littérature mauritanienne"
        }
    },
    {
        id: 7,
        title: "Les Chroniques de Narnia",
        author: "C.S. Lewis",
        price: 700,
        category: "jeunesse",
        image: "images/books/narnia.jpg",
        isNew: true,
        isBestseller: true,
        description: "Quatre enfants libèrent Narnia.",
        resume: "Les frères et sœurs Peter, Susan, Edmund et Lucy ont été envoyés à la campagne afin qu'ils échappent aux bombardements, chez un vieux professeur. C'est là qu'ils découvrent un monde magique appelé Narnia, où les animaux parlent et où la magie existe. Une aventure fantastique qui a marqué des générations.",
        details: {
            ean: "9782070659142",
            isbn: "2070659144",
            contributeurs: "C.S. Lewis (Auteur principal)",
            format: "Livre broché",
            nbPages: 800,
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.5 cm",
            longueur: "18 cm",
            epaisseur: "2.5 cm",
            poids: "0.400 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Fantasy"
        }
    },
    {
        id: 8,
        title: "La Sélection",
        author: "Kiera Cass",
        price: 550,
        category: "roman",
        image: "images/books/la-selection.jpg",
        isNew: true,
        isBestseller: false,
        description: "America Singer.",
        resume: "35 candidates. 1 couronne. La compétition de leur vie. Pour les jeunes filles choisies, la Sélection représente une chance unique de troquer un destin. Dans un futur sombre, sur les ruines des États-Unis, un jeu... La compétition de leur vie pour gagner le cœur du prince.",
        details: {
            ean: "9782266260580",
            isbn: "2266260588",
            contributeurs: "Kiera Cass (Auteur principal)",
            format: "Livre poche",
            nbPages: 384,
            editeur: "Pocket Jeunesse",
            collection: "Pocket Jeunesse",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.8 cm",
            poids: "0.230 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Romance"
        }
    },
    {
        id: 9,
        title: "Vampire Academy",
        author: "Richelle Mead",
        price: 600,
        category: "roman",
        image: "images/books/vampire-academy.jpg",
        isNew: true,
        isBestseller: false,
        description: "Rose protège Lissa.",
        resume: "Rose Hathaway est une Dhampir, vouée à protéger les vampires Moroï. Son amie Lissa est une princesse Moroï. Ensemble, elles tentent de survivre dans un monde où les dangers sont partout. Un best-seller international adapté au cinéma.",
        details: {
            ean: "9782266215429",
            isbn: "2266215426",
            contributeurs: "Richelle Mead (Auteur principal)",
            format: "Livre poche",
            nbPages: 480,
            editeur: "Pocket Jeunesse",
            collection: "Pocket Jeunesse",
            largeur: "11 cm",
            longueur: "18 cm",
            epaisseur: "1.8 cm",
            poids: "0.250 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Fantasy"
        }
    },
    {
        id: 10,
        title: "Le livre des étoiles",
        author: "Erik L'Homme",
        price: 500,
        category: "roman",
        image: "images/books/livre-etoiles.jpg",
        isNew: true,
        isBestseller: false,
        description: "Robin et Qadehar.",
        resume: "Guillemot de Troïl est un garçon du pays d'Ys, situé à mi-chemin entre le Monde Réel et le Monde Incertain. D'où lui viennent ses dons pour la sorcellerie ? Une trilogie de fantasy pour la jeunesse qui a marqué toute une génération.",
        details: {
            ean: "9782070545810",
            isbn: "2070545815",
            contributeurs: "Erik L'Homme (Auteur principal)",
            format: "Livre poche",
            nbPages: 252,
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.5 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Fantasy jeunesse"
        }
    },
    {
        id: 11,
        title: "Comme toi",
        author: "Lisa Jewell",
        price: 1000,
        category: "roman",
        image: "images/books/comme-toi.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une fillette au visage d'une disparue.",
        resume: "Une troublante impression de déjà-vu... Ellie a disparu à l'âge de quinze ans. Sa mère n'a jamais réussi à faire son deuil, d'autant plus que la police n'a retrouvé ni le coupable ni le corps. Dix ans plus tard, cette femme brisée doit pourtant se résoudre à tourner la page. C'est alors qu'elle fait la connaissance de Floyd, un homme charmant, père célibataire, auquel elle se lie peu à peu. Mais lorsqu'elle rencontre la fille de celui-ci, Poppy, âgée de neuf ans, le passé la rattrape brutalement : cette fillette est le portrait craché de sa fille disparue...",
        details: {
            ean: "9782811226671",
            isbn: "2811226672",
            contributeurs: "Lisa Jewell (Auteur principal)",
            format: "Livre",
            nbPages: 384,
            editeur: "Milady",
            collection: "HAUTEVILLE SUSP",
            largeur: "14.4 cm",
            longueur: "21.3 cm",
            epaisseur: "2.5 cm",
            poids: "0.385 kg",
            impression: "Non",
            categories: "Livres, Littérature anglophone, Romans et Littérature, Polars, thrillers et romans d'espionnage"
        }
    },
    {
        id: 12,
        title: "Le prince de la brume",
        author: "Carlos Ruiz Zafón",
        price: 550,
        category: "roman",
        image: "images/books/prince-brume.jpg",
        isNew: true,
        isBestseller: false,
        description: "Max et le Prince de la Brume.",
        resume: "1943, Angleterre. Fuyant la guerre, la famille Carver se réfugie dans un village de bord de mer. Leur nouvelle maison appartenait à un couple riche qui a quitté le pays après la mort de leur fils Jacob. Max, le fils aîné, découvre un jardin rempli de statues étranges et un mystérieux personnage : le Prince de la Brume. Doté de pouvoirs diaboliques, le Prince de la Brume réclame le paiement d'une dette contractée avant la naissance de Jacob. S'ils veulent sauver leur ami Roland, Max et Alicia doivent affronter l'être maléfique sur son territoire.",
        details: {
            ean: "9782221122891",
            isbn: "2221122895",
            contributeurs: "Carlos Ruiz Zafon (Auteur principal)",
            format: "Livre",
            nbPages: 209,
            editeur: "Robert Laffont",
            largeur: "13.7 cm",
            longueur: "21.6 cm",
            epaisseur: "1.9 cm",
            poids: "0.264 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Littérature hispanophone"
        }
    },
    {
        id: 13,
        title: "Oksa Pollock",
        author: "Anne Plichota, Cendrine Wolf",
        price: 600,
        category: "roman",
        image: "images/books/oksa-pollock.jpg",
        isNew: true,
        isBestseller: false,
        description: "Oksa et ses dons.",
        resume: "Oksa Pollock, 13 ans, pensait être comme tout le monde, mais ce soir tout a changé. Un peu angoissée par la rentrée dans son nouveau collège, Oksa déclenche tout à coup des phénomènes étranges dans sa chambre. Un coin de son bureau prend feu, ses cartons de déménagement explosent. Elle qui a toujours rêvé d'être une ninja, voilà qu'elle se découvre des dons surnaturels ! Sa grand-mère, l'excentrique Dragomira, lui avoue le secret de ses origines : la famille Pollock vient d'Édéfia, un monde invisible caché quelque part sur Terre. Oksa est leur Inespérée, leur seul espoir d'y retourner.",
        details: {
            ean: "9782845634602",
            isbn: "2845634609",
            contributeurs: "Anne Plichota (Auteur principal), Cendrine Wolf (Auteur principal)",
            format: "Livre",
            nbPages: 485,
            editeur: "XO",
            largeur: "15.5 cm",
            longueur: "24.2 cm",
            epaisseur: "3.7 cm",
            poids: "0.612 kg",
            impression: "Non",
            saga: "Oksa Pollock",
            categories: "Livres, Jeunesse"
        }
    },
    {
        id: 14,
        title: "Meurtre mode d'emploi",
        author: "Holly Jackson",
        price: 650,
        category: "roman",
        image: "images/books/meurtre-mode-emploi.jpg",
        isNew: true,
        isBestseller: false,
        description: "Pip enquête.",
        resume: "Il y a cinq ans, Sal Singh s'est accusé du meurtre de sa petite amie, Andie Bell, avant de se donner la mort. La police est sûre que l'affaire est résolue. Toute la ville aussi. Mais Pippa, une lycéenne de 17 ans passionnée par le true crime, décide de mener sa propre enquête. Elle déterre un à un des secrets compromettants sur Andie. La liste des suspects se rallonge. Mais à trop s'approcher de la vérité, Pippa alerte aussi le véritable meurtrier... se mettant elle-même en danger.",
        details: {
            ean: "9782203228610",
            isbn: "220322861X",
            contributeurs: "Holly Jackson (Auteur principal)",
            format: "Livre",
            nbPages: 528,
            editeur: "Casterman",
            collection: "ROMANS JUNIOR",
            largeur: "14.5 cm",
            longueur: "21.9 cm",
            epaisseur: "3.5 cm",
            poids: "0.548 kg",
            impression: "Non",
            saga: "Meurtre mode d'emploi",
            categories: "Livres, Jeunesse, Adolescents, Adolescents et jeunes adultes"
        }
    },
    {
        id: 15,
        title: "L'Arbre à la cour criminelle",
        author: "Djibril Hamet Ly",
        price: 300,
        category: "théatre",
        image: "images/books/arbre-cours.jpg",
        isNew: true,
        isBestseller: false,
        description: "Enquête en Sologne.",
        resume: "Une pièce de théâtre captivante qui explore les thèmes de la justice, de la tradition et de la modernité en Mauritanie. L'arbre à la cour criminelle est le témoin silencieux des drames humains qui se jouent sous ses branches.",
        details: {
            ean: "9782343178907",
            isbn: "2343178906",
            contributeurs: "Djibril Hamet Ly (Auteur principal)",
            format: "Livre broché",
            nbPages: 120,
            editeur: "Editions L'Harmattan",
            collection: "Études africaines",
            largeur: "13.5 cm",
            longueur: "21.5 cm",
            epaisseur: "1 cm",
            poids: "0.180 kg",
            impression: "Non",
            categories: "Livres, Théâtre, Littérature africaine"
        }
    },
    {
        id: 16,
        title: "Je veux parler",
        author: "Djibril zakaria sall",
        price: 300,
        category: "poésie",
        image: "images/books/je-veux-parler.jpg",
        isNew: true,
        isBestseller: false,
        description: "28 nouvelles-poésies.",
        resume: "Ancien commissaire de police, Djibril Zakaria Sall faisait des dictées à ses prisonniers. Son recueil de poésies 'Je veux parler' est une anthologie poétique qui couvre la période 1967-2012. Une voix unique de la littérature mauritanienne.",
        details: {
            ean: "9782343172356",
            isbn: "2343172357",
            contributeurs: "Djibril Zakaria Sall (Auteur principal)",
            format: "Livre broché",
            nbPages: 167,
            editeur: "Editions de la Librairie 15/21",
            collection: "Lettres Mauritaniennes",
            largeur: "13.5 cm",
            longueur: "21.5 cm",
            epaisseur: "1 cm",
            poids: "0.200 kg",
            impression: "Non",
            categories: "Livres, Poésie, Littérature mauritanienne"
        }
    },

    // ============================================================
    // DÉVELOPPEMENT PERSONNEL (17 à 24)
    // ============================================================
    {
        id: 17,
        title: "L'autoroute du millionnaire",
        author: "MJ DeMarco",
        price: 2000,
        category: "developpement",
        image: "images/books/autoroute-millionnaire.jpg",
        isNew: true,
        isBestseller: true,
        description: "Devenez riche rapidement.",
        resume: "Allez à l'école, obtenez de bons diplômes et un poste de cadre. Achetez votre résidence principale dès que possible, limitez les dépenses au maximum et épargnez 10% de vos revenus. Si vous suivez ces recommandations, vous serez peut-être riche un jour... mais pas avant de nombreuses années ! Ou bien, oubliez ces conseils et devenez riche maintenant. MJ DeMarco, entrepreneur parti de zéro, est devenu multimillionnaire en respectant les 5 commandements qui mènent vers la richesse.",
        details: {
            ean: "9782849334652",
            isbn: "2849334650",
            contributeurs: "MJ DeMarco (Auteur principal), Florence Logerot-depraz (Traducteur)",
            format: "Livre",
            nbPages: 501,
            editeur: "Contre-Dires",
            largeur: "15.4 cm",
            longueur: "23.1 cm",
            epaisseur: "2.8 cm",
            poids: "0.726 kg",
            impression: "Non",
            categories: "Livres, Guides pratiques de développement personnel, Gestion de fortune et patrimoine"
        }
    },
    {
        id: 18,
        title: "Père riche, père pauvre",
        author: "Robert Kiyosaki",
        price: 2500,
        category: "developpement",
        image: "images/books/pere-riche-pere-pauvre.jpg",
        isNew: true,
        isBestseller: true,
        description: "Les clés de la réussite financière.",
        resume: "Père riche, Père pauvre est le meilleur ouvrage de tous les temps en matière de finances personnelles ! Il brise le mythe selon lequel il faut gagner beaucoup d'argent pour devenir riche, remet en question la croyance voulant que votre maison est un actif, et explique aux parents pourquoi ils ne doivent pas se fier au système d'éducation pour enseigner les rudiments de l'argent à leurs enfants.",
        details: {
            ean: "9782892259551",
            isbn: "289225955X",
            contributeurs: "Robert T. Kiyosaki (Auteur principal)",
            format: "Livre",
            nbPages: 336,
            editeur: "UN MONDE DIFFERENT",
            largeur: "15.3 cm",
            longueur: "22.9 cm",
            epaisseur: "2.4 cm",
            poids: "0.38 kg",
            impression: "Non",
            categories: "Livres, Gestion de fortune et patrimoine, Méditation et développement personnel"
        }
    },
    {
        id: 19,
        title: "Réfléchissez et devenez riche",
        author: "Napoleon Hill",
        price: 2000,
        category: "developpement",
        image: "images/books/reflechissez-devenez-riche.jpg",
        isNew: true,
        isBestseller: true,
        description: "Les 13 principes de la réussite.",
        resume: "Vous trouverez dans ce livre ce que personne ne vous enseignera jamais ailleurs : comment assimiler et appliquer les principes qui vous permettront de faire fortune et d'atteindre les buts que vous vous êtes fixés. Napoleon Hill parvient avec brio à démontrer comment vos pensées et vos croyances peuvent changer le cours de votre vie. Fruit d'une recherche de plus de vingt ans, Réfléchissez et devenez riche développe treize principes universels qui vous mèneront vers une réussite garantie.",
        details: {
            ean: "9782290028827",
            isbn: "2290028827",
            contributeurs: "Napoleon Hill (Auteur principal)",
            format: "Livre poche",
            nbPages: 224,
            editeur: "J'ai lu",
            collection: "Bien-être",
            largeur: "11 cm",
            longueur: "17.8 cm",
            epaisseur: "1.3 cm",
            poids: "0.166 kg",
            impression: "Non",
            categories: "Livres, Beauté, santé et bien-être, Sciences Humaines, Coaching professionnel"
        }
    },
    {
        id: 20,
        title: "Atomic Habits",
        author: "James Clear",
        price: 1500,
        category: "developpement",
        image: "images/books/atomic-habits.jpg",
        isNew: true,
        isBestseller: true,
        description: "Changez vos habitudes.",
        resume: "Vous avez du mal à changer vos habitudes ? Le problème ne vient pas de vous, mais des moyens que vous utilisez. Les mauvaises habitudes se répètent non pas parce que vous ne voulez pas changer, mais parce que vous utilisez des moyens incompatibles avec le changement. James Clear, expert mondial en matière de création d'habitudes, vous offre des stratégies pratiques pour créer de bonnes habitudes et abandonner les mauvaises, grâce à de petits changements quotidiens.",
        details: {
            ean: "9782035969200",
            isbn: "2035969204",
            contributeurs: "James Clear (Auteur principal), Emmanuelle Hautbois (Traducteur)",
            format: "Livre",
            nbPages: 320,
            editeur: "Larousse",
            collection: "ESSAIS - DEVELO",
            largeur: "14.2 cm",
            longueur: "22.5 cm",
            epaisseur: "2.5 cm",
            poids: "0.422 kg",
            impression: "Non",
            categories: "Livres, Guides pratiques de développement personnel, Questions de société, Coaching professionnel"
        }
    },
    {
        id: 21,
        title: "Les 4 accords toltèques",
        author: "Don Miguel Ruiz",
        price: 600,
        category: "developpement",
        image: "images/books/4-accords-tolteques.jpg",
        isNew: true,
        isBestseller: false,
        description: "Sagesse toltèque.",
        resume: "Don Miguel Ruiz révèle la source des croyances limitatrices qui nous privent de joie et créent des souffrances inutiles. Il montre en des termes très simples comment se libérer du conditionnement collectif afin de retrouver la dimension d'amour inconditionnel. Les quatre accords proposent un puissant code de conduite capable de transformer rapidement notre vie en une expérience de liberté, de vrai bonheur et d'amour.",
        details: {
            ean: "9782889116546",
            isbn: "2889116549",
            contributeurs: "Miguel Ruiz (Auteur principal)",
            format: "Livre poche",
            nbPages: 141,
            editeur: "Jouvence",
            collection: "Poche",
            largeur: "10.8 cm",
            longueur: "17.8 cm",
            epaisseur: "1.3 cm",
            poids: "0.126 kg",
            impression: "Non",
            categories: "Livres, Guides pratiques de développement personnel, Chamanisme"
        }
    },
    {
        id: 22,
        title: "L'Art subtil de s'en foutre",
        author: "Mark Manson",
        price: 1000,
        category: "developpement",
        image: "images/books/art-subtil-sen-foutre.webp",
        isNew: true,
        isBestseller: true,
        description: "Choisissez vos combats.",
        resume: "Le discours ambiant nous pousse sans cesse à nous améliorer. Mais il faut en finir avec la pensée positive, nous dit Mark Manson. Soyons honnêtes : parfois tout va de travers, et il faut faire avec. C'est en regardant en face nos peurs, nos défauts et nos incertitudes que nous pourrons trouver le courage et la confiance qui nous manquent tant. Un livre-manifeste pour construire des vies plus réjouissantes, plus ancrées.",
        details: {
            ean: "9782212567595",
            isbn: "2212567596",
            contributeurs: "Mark Manson (Auteur principal)",
            format: "Livre",
            nbPages: 188,
            editeur: "Eyrolles",
            largeur: "13.7 cm",
            longueur: "21.5 cm",
            epaisseur: "1.5 cm",
            poids: "0.238 kg",
            impression: "Non",
            categories: "Livres, Guides pratiques de développement personnel, Coaching professionnel"
        }
    },
    {
        id: 23,
        title: "Les 7 habitudes des gens efficaces",
        author: "Stephen Covey",
        price: 1500,
        category: "developpement",
        image: "images/books/7-habitudes.webp",
        isNew: true,
        isBestseller: false,
        description: "Management et productivité.",
        resume: "Pensez gagnant, changez ! Cette méthode développée par Stephen R. Covey propose une approche qui opère sur les leviers de l'efficacité personnelle et interpersonnelle. Le programme des Sept Habitudes fournit des pistes de réflexion et des exercices pour tirer le meilleur parti de soi-même, des autres et de toutes les situations d'interdépendance.",
        details: {
            ean: "9782895584315",
            isbn: "2895584311",
            contributeurs: "Sean Covey (Auteur principal)",
            format: "CD-ROM",
            editeur: "STANKE ALEXANDRE",
            poids: "0.075 kg",
            impression: "Non",
            categories: "Livres, Activités manuelles et artistiques, Romans, Autres Livres"
        }
    },
    {
        id: 24,
        title: "La Semaine de 4 heures",
        author: "Tim Ferriss",
        price: 600,
        category: "developpement",
        image: "images/books/semaine-4-heures.webp",
        isNew: true,
        isBestseller: false,
        description: "Vivez mieux en travaillant moins.",
        resume: "Le guide pratique pour améliorer radicalement sa vie et faire ce que l'on aime, tout en ayant plus de temps et plus d'argent. Timothy Ferriss vous démontre qu'il est possible de diviser son temps de travail par quatre tout en augmentant ses revenus.",
        details: {
            ean: "9782744064173",
            isbn: "2744064173",
            contributeurs: "Timothy Ferriss (Auteur principal)",
            format: "Livre",
            nbPages: 390,
            editeur: "Pearson",
            collection: "Efficacite prof",
            largeur: "17 cm",
            longueur: "21 cm",
            epaisseur: "2.1 cm",
            poids: "0.58 kg",
            impression: "Non",
            categories: "Livres, Ressources humaines - RH, Réussite professionnelle, Coaching professionnel"
        }
    },

    // ============================================================
    // THRILLERS (25 à 28)
    // ============================================================
    {
        id: 25,
        title: "La Psy",
        author: "Freida McFadden",
        price: 600,
        category: "thriller",
        image: "images/books/la-psy.jpg",
        isNew: true,
        isBestseller: false,
        description: "Tricia et Ethan piégés.",
        resume: "Jeunes mariés, Tricia et Ethan recherchent la maison de leurs rêves. Alors qu'ils visitent le manoir isolé de la docteure Adrienne Hale, une psychiatre disparue trois ans plus tôt, ils se retrouvent piégés par une violente tempête de neige. Tricia découvre une pièce secrète qui renferme les enregistrements audio de chaque patient. Le voile de mystère qui recouvre la disparition de la psy se lève lentement. Mais déterrer des secrets enfouis est un jeu dangereux...",
        details: {
            ean: "9782290415627",
            isbn: "2290415626",
            contributeurs: "Freida McFadden (Auteur principal), Karine Forestier (Traducteur)",
            format: "Livre poche",
            nbPages: 416,
            editeur: "J'ai lu",
            collection: "Policier",
            largeur: "11 cm",
            longueur: "17.8 cm",
            epaisseur: "2.2 cm",
            poids: "0.224 kg",
            impression: "Non",
            categories: "Polars, thrillers et romans d'espionnage, Livres, Polars, thrillers et romans d'espionnage étrangers"
        }
    },
    {
        id: 26,
        title: "La Conversion",
        author: "James Baldwin",
        price: 500,
        category: "thriller",
        image: "images/books/la-conversion.jpg",
        isNew: true,
        isBestseller: false,
        description: "John Grimes.",
        resume: "Au soir de ses quatorze ans, au milieu des prières cadencées de ses frères, John Grimes traverse un moment essentiel, entre crise spirituelle et épiphanie. Selon sa famille, son destin est scellé : il sera prédicateur. Mais John veut mener sa vie comme il l'entend. Le libre arbitre existe-t-il pour un jeune Noir en Amérique ? Dans ce premier roman autobiographique, James Baldwin raconte à la fois son expérience et une odyssée collective.",
        details: {
            ean: "9782253250746",
            isbn: "2253250740",
            contributeurs: "James Baldwin (Auteur principal), Michele Albaret-maatsch (Traducteur)",
            format: "Livre poche",
            nbPages: 352,
            editeur: "Le Livre de Poche",
            collection: "Biblio romans",
            largeur: "11 cm",
            longueur: "17.8 cm",
            epaisseur: "1.6 cm",
            poids: "0.184 kg",
            impression: "Non",
            categories: "Romans et Littérature, Livres"
        }
    },
    {
        id: 27,
        title: "Le Joueur d'échecs",
        author: "Stefan Zweig",
        price: 300,
        category: "thriller",
        image: "images/books/le-joueur-dechecs.jpg",
        isNew: true,
        isBestseller: true,
        description: "Czentovic.",
        resume: "Qui est cet inconnu capable d'en remontrer au grand Czentovic, le champion mondial des échecs ? Le narrateur découvrira les circonstances terribles dans lesquelles l'inconnu a acquis cette science : les expérimentations nazies sur l'isolement absolu, où, aux frontières de la folie, le cerveau humain parvient à déployer ses facultés les plus étranges. Une fable inquiétante, fantastique, qui pourrait servir d'illustration à la charmante époque où nous vivons.",
        details: {
            ean: "9782253174073",
            isbn: "2253174076",
            contributeurs: "Stefan Zweig (Auteur principal), Brigitte Vergne-Cain (Traducteur)",
            format: "Livre poche",
            nbPages: 128,
            editeur: "Le Livre de Poche",
            collection: "Littérature",
            largeur: "11 cm",
            longueur: "17.8 cm",
            epaisseur: "1 cm",
            poids: "0.108 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature"
        }
    },
    {
        id: 28,
        title: "Les P'tites Poules",
        author: "Christian Jolibois",
        price: 350,
        category: "thriller",
        image: "images/books/ptites-poules.jpg",
        isNew: true,
        isBestseller: false,
        description: "Carmen et Carmélito.",
        resume: "Rien ne va plus au poulailler : Pitikok n'arrive pas à faire lever le soleil ! Comme tous les matins, le papa de Carmen et de Carmélito a lancé son appel vers le ciel : 'Cocorico !' Mais rien ne se passe. L'astre solaire a disparu. Qu'à cela ne tienne : Carmen, Carmélito et Bélino retrouveront le soleil ! Nom d'une poule !",
        details: {
            ean: "9782266156639",
            isbn: "2266156632",
            contributeurs: "Christian Jolibois (Auteur principal), Christian Heinrich (Auteur principal)",
            format: "Livre poche",
            nbPages: 48,
            editeur: "Pocket Jeunesse",
            collection: "COLLECTION 6/9 ANS",
            largeur: "15.1 cm",
            longueur: "19.1 cm",
            epaisseur: "6 mm",
            poids: "0.11 kg",
            impression: "Non",
            saga: "Les P'tites poules",
            categories: "Livres, Premières lectures, Lectures pour les 7-12 ans, Albums illustrés"
        }
    },

    // ============================================================
    // POÉSIE (29 à 34)
    // ============================================================
    {
        id: 29,
        title: "Le Petit Prince",
        author: "Antoine de Saint-Exupéry",
        price: 500,
        category: "poesie",
        image: "images/books/le-petit-prince.jpg",
        isNew: true,
        isBestseller: true,
        description: "Conte philosophique.",
        resume: "J'ai ainsi vécu seul, sans personne avec qui parler véritablement, jusqu'à une panne dans le désert du Sahara, il y a six ans. Le premier soir je me suis endormi sur le sable à mille milles de toute terre habitée. Alors vous imaginez ma surprise, au lever du jour, quand une drôle de petite voix m'a réveillé. Elle disait : 'S'il vous plaît... dessine-moi un mouton !'",
        details: {
            ean: "9782070408504",
            isbn: "2070408507",
            contributeurs: "Antoine de Saint-Exupéry (Auteur principal)",
            format: "Livre poche",
            nbPages: 104,
            editeur: "Folio",
            collection: "Folio",
            largeur: "11 cm",
            longueur: "15 cm",
            epaisseur: "7 mm",
            poids: "0.123 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Littérature française"
        }
    },
    {
        id: 30,
        title: "Une saison en enfer",
        author: "Arthur Rimbaud",
        price: 500,
        category: "poesie",
        image: "images/books/saison-enfer.jpg",
        isNew: true,
        isBestseller: false,
        description: "Poésie en prose.",
        resume: "Ce livre incandescent est le résumé d'une quête et d'une crise : quête de la vérité, crise d'un jeune homme et d'une société, crise du langage, de la culture et de la foi. Crise signifie jugement : jugement porté sur ce qu'on a cru, désillusion qui conduit à l'initiation, à la liberté de posséder la vérité dans une âme et un corps.",
        details: {
            ean: "9782910233150",
            isbn: "2910233154",
            contributeurs: "Arthur Rimbaud (Auteur principal)",
            format: "Livre poche",
            nbPages: 64,
            editeur: "Mille et Une Nuits",
            collection: "La petite collection",
            poids: "0.05 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Poésie"
        }
    },
    {
        id: 31,
        title: "Capitale de la douleur",
        author: "Paul Éluard",
        price: 500,
        category: "poesie",
        image: "images/books/capitale-douleur.jpg",
        isNew: true,
        isBestseller: false,
        description: "Surréalisme.",
        resume: "Fruit de cinq années de production poétique, Capitale de la douleur (1926) est l'un des recueils les plus célèbres de Paul Éluard. S'y trouve retracé le parcours initiatique d'un jeune poète, qui exorcise son désespoir par la recherche d'un verbe pur, simple et enchanteur. La poésie qui en résulte est, pour André Breton, un miracle, un secret qui prend les couleurs de l'éternité.",
        details: {
            ean: "9782080424563",
            isbn: "2080424564",
            contributeurs: "Paul Éluard (Auteur principal)",
            format: "Livre poche",
            nbPages: 288,
            editeur: "Flammarion",
            collection: "Gf poesie",
            largeur: "17.8 cm",
            longueur: "10.8 cm",
            epaisseur: "1.3 cm",
            poids: "0.148 kg",
            impression: "Non",
            categories: "Romans et Littérature, Livres, Poésie"
        }
    },
    {
        id: 32,
        title: "Le Prophète",
        author: "Khalil Gibran",
        price: 500,
        category: "poesie",
        image: "images/books/prophete.jpg",
        isNew: true,
        isBestseller: false,
        description: "Amour, travail, liberté.",
        resume: "Après douze ans d'exil, son navire est enfin arrivé. La mer l'appelle. Bientôt, Almustafa reverra son île natale. Mais il ne quittera pas la cité d'Orphalèse sans dispenser à son peuple les enseignements de sa profonde sagesse. Amour, mariage, liberté, travail, mort... Ce qui bouge en nos âmes n'a pas de secret pour lui, qui connaît les rêves du vent et le cœur de Dieu.",
        details: {
            ean: "9782266294546",
            isbn: "2266294547",
            contributeurs: "Khalil Gibran (Auteur principal), Didier Senecal (Traducteur)",
            format: "Livre poche",
            nbPages: 96,
            editeur: "Pocket",
            collection: "Classiques Pocket",
            largeur: "10.9 cm",
            longueur: "17.9 cm",
            epaisseur: "9 mm",
            poids: "0.07 kg",
            impression: "Non",
            categories: "Livres, Romans et Littérature, Poésie"
        }
    },
    {
        id: 33,
        title: "Les Fleurs du Mal",
        author: "Charles Baudelaire",
        price: 500,
        category: "poesie",
        image: "images/books/les-fleurs-du-mal.jpg",
        isNew: true,
        isBestseller: true,
        description: "Symbolisme.",
        resume: "Plonger au fond du gouffre, Enfer ou Ciel, qu'importe ? Au fond de l'inconnu, pour trouver du nouveau ! Ces vers du Voyage éclairent à eux seuls l'entreprise du poète. Baudelaire explore les dédales de la conscience, atteint tantôt à l'extase, tantôt se perd dans les abîmes du péché. À travers ses poèmes, il nous fait partager le drame qui se joue en lui et qui n'est autre que la tragédie humaine.",
        details: {
            ean: "9782070307661",
            isbn: "2070307662",
            contributeurs: "Charles Baudelaire (Auteur principal)",
            format: "Livre poche",
            nbPages: 352,
            editeur: "Gallimard",
            collection: "Poésie/Gallimard",
            largeur: "10.8 cm",
            longueur: "17.8 cm",
            epaisseur: "1.7 cm",
            poids: "0.282 kg",
            impression: "Non",
            categories: "Livres, Poésie"
        }
    },
    {
        id: 34,
        title: "Fureur et Mystère",
        author: "René Char",
        price: 500,
        category: "poesie",
        image: "images/books/fureur-mystere.jpg",
        isNew: true,
        isBestseller: false,
        description: "Résistance.",
        resume: "Pourquoi le cacher ? Ce n'est pas une poésie facile. Ses difficultés sont à proportion, en nous, des vieilles habitudes de voir et de leur résistance : René Char ou la jeunesse des mots, du monde... Il faut le lire et le relire pour, peu à peu, sentir en soi la débâcle des vieilles digues, de l'imagination paresseuse. Poésie qui se gagne, comme la terre promise de la légende et de l'histoire.",
        details: {
            ean: "9782070300655",
            isbn: "207030065X",
            contributeurs: "Rene Char (Auteur principal)",
            format: "Livre poche",
            nbPages: 224,
            editeur: "Gallimard",
            collection: "Poésie/Gallimard",
            largeur: "10.8 cm",
            longueur: "17.8 cm",
            epaisseur: "1.1 cm",
            poids: "0.186 kg",
            impression: "Non",
            categories: "Livres, Poésie"
        }
    },

    // ============================================================
    // MANGAS (35 à 44)
    // ============================================================
    {
        id: 35,
        title: "One Piece – Tome 1",
        author: "Eiichiro Oda",
        price: 500,
        category: "manga",
        image: "images/books/one-piece-tome1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Luffy veut devenir Roi des Pirates.",
        resume: "Nous sommes à l'ère des pirates. Luffy, un garçon espiègle, rêve de devenir le roi des pirates en trouvant le 'One Piece', un fabuleux trésor. Il a avalé un fruit du démon qui l'a transformé en homme-caoutchouc. Depuis, il est capable de contorsionner son corps dans tous les sens, mais il a perdu la faculté de nager. Avec l'aide de ses précieux amis, il va devoir affronter de redoutables pirates dans des aventures toujours plus rocambolesques.",
        details: {
            ean: "9782723488525",
            isbn: "2723488527",
            contributeurs: "Eiichirō Oda (Auteur principal)",
            format: "Livre poche",
            nbPages: 208,
            editeur: "Glénat",
            collection: "Shōnen",
            largeur: "11.5 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.15 kg",
            impression: "Non",
            saga: "One Piece",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 36,
        title: "Chainsaw Man – Tome 1",
        author: "Tatsuki Fujimoto",
        price: 600,
        category: "manga",
        image: "images/books/chainsaw-man-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Denji et son démon.",
        resume: "Pour rembourser ses dettes, Denji, jeune homme dans la dèche la plus totale, est exploité en tant que Devil Hunter avec son chien-démon-tronçonneuse, 'Pochita'. Mais suite à une cruelle trahison, il voit enfin une possibilité de se tirer des bas-fonds où il croupit ! Devenu surpuissant après sa fusion avec Pochita, Denji est recruté par une organisation de Devil Hunters et part à la chasse aux démons.",
        details: {
            ean: "9782820337825",
            isbn: "2820337821",
            contributeurs: "Tatsuki Fujimoto (Auteur principal), Sebastien Ludmann (Traducteur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Crunchyroll",
            collection: "Shonen up!",
            largeur: "11.5 cm",
            longueur: "17.7 cm",
            epaisseur: "1.3 cm",
            poids: "0.13 kg",
            impression: "Non",
            saga: "Chainsaw Man",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen, Seinen, Josei"
        }
    },
    {
        id: 37,
        title: "l'attaque des Titans – Tome 1",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren contre les Titans.",
        resume: "Le monde appartient désormais aux Titans, des êtres gigantesques qui ont presque décimé l'Humanité. Voilà une centaine d'années, les derniers rescapés ont bâti une place forte, une cité cernée d'une haute muraille. Hélas, cette illusion de sécurité vole en éclats le jour où surgit un Titan démesuré, encore bien plus colossal que tous les autres. S'engage alors un combat désespéré pour la survie du genre humain.",
        details: {
            ean: "9782811611699",
            isbn: "281161169X",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Pika Seinen",
            largeur: "12 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.188 kg",
            impression: "Non",
            saga: "L'Attaque des Titans",
            categories: "Livres, Mangas, Manwha, Man Hua, Seinen, Josei"
        }
    },
    {
        id: 38,
        title: "Naruto – Tome 1",
        author: "Masashi Kishimoto",
        price: 500,
        category: "manga",
        image: "images/books/naruto-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Le ninja au démon-renard.",
        resume: "Naruto est un garçon un peu spécial. Il est toujours tout seul et son caractère fougueux ne l'aide pas vraiment à se faire apprécier dans son village. Malgré cela, il garde au fond de lui une ambition : celle de devenir un maître Hokage, la plus haute distinction dans l'ordre des ninjas, et ainsi obtenir la reconnaissance de ses pairs.",
        details: {
            ean: "9782871294146",
            isbn: "2871294143",
            contributeurs: "Masashi Kishimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Kana",
            collection: "Shōnen",
            largeur: "12 cm",
            longueur: "17.5 cm",
            epaisseur: "1.4 cm",
            poids: "0.138 kg",
            impression: "Non",
            saga: "Naruto",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 39,
        title: "Dragon Ball – Tome 1",
        author: "Akira Toriyama",
        price: 500,
        category: "manga",
        image: "images/books/dragon-ball-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Son Goku et les Dragon Balls.",
        resume: "Les dragon balls sont des boules de cristal magiques. Celui qui les réunit invoque un dragon qui réalisera ses vœux. Sangoku, Dendé, Végéta et tous les protagonistes de cette grande saga tentent de trouver les sept dragon balls qui, une fois le vœu exaucé, s'éparpilleront à nouveau dans l'univers.",
        details: {
            ean: "9782876952058",
            isbn: "287695205X",
            contributeurs: "Akira Toriyama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Glénat",
            collection: "Shōnen",
            largeur: "11.5 cm",
            longueur: "18 cm",
            poids: "0.135 kg",
            impression: "Non",
            saga: "Dragon Ball",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 40,
        title: "Demon Slayer – Tome 1",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Tanjiro sauve sa sœur.",
        resume: "Le Japon, au début du XXe siècle. Un jeune vendeur de charbon nommé Tanjiro mène une vie sans histoire dans les montagnes, jusqu'au jour tragique où il découvre son village et sa famille massacrés par un démon. La seule survivante est sa jeune sœur Nezuko, qui s'est métamorphosée en monstre féroce. Afin de renverser le processus et de venger sa famille, Tanjiro décide de partir en quête de vérité.",
        details: {
            ean: "9782809482317",
            isbn: "2809482314",
            contributeurs: "Koyoharu Gotôge (Auteur principal), Arnaud Takahashi (Traducteur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            largeur: "11.6 cm",
            longueur: "17.5 cm",
            epaisseur: "1.7 cm",
            poids: "0.155 kg",
            impression: "Non",
            saga: "Demon Slayer",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 41,
        title: "Fruits Basket – Tome 1",
        author: "Natsuki Takaya",
        price: 500,
        category: "manga",
        image: "images/books/fruits-basket-1.jpg",
        isNew: true,
        isBestseller: false,
        description: "La malédiction du zodiaque.",
        resume: "Tohru, orpheline de seize ans, a décidé d'être totalement indépendante. Elle installe une grande tente au milieu d'un terrain en friche. Malheureusement, le terrain appartient aux Sôma, une famille maudite, dont les membres se transforment en l'un des douze animaux du zodiaque chinois à chaque fois qu'ils sont trop fatigués ou approchés de près par une personne du sexe opposé ! Tohru est la première à percer leur secret.",
        details: {
            ean: "9782413000778",
            isbn: "2413000771",
            contributeurs: "Natsuki Takaya (Auteur principal)",
            format: "Livre poche",
            nbPages: 392,
            editeur: "Delcourt",
            collection: "SHOJO DELCOURT/TONKAM",
            largeur: "12.8 cm",
            longueur: "18.2 cm",
            epaisseur: "2.7 cm",
            poids: "0.37 kg",
            impression: "Non",
            saga: "Fruits basket",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōjo"
        }
    },
    {
        id: 42,
        title: "Sailor Moon – Tome 1",
        author: "Naoko Takeuchi",
        price: 500,
        category: "manga",
        image: "images/books/sailor-moon-1.jpg",
        isNew: true,
        isBestseller: false,
        description: "Usagi, guerrière magique.",
        resume: "Usagi est une jeune fille de 14 ans comme tant d'autres : elle aime dormir, jouer aux jeux vidéo, elle pleure pour un oui ou pour un non et elle ne se passionne pas pour ses études. Mais un beau jour, elle croise le chemin de Luna, un chat doué de parole qui va la transformer en une jolie justicière : Sailor Moon ! La voilà investie de plusieurs missions, tout en luttant contre de mystérieux ennemis.",
        details: {
            ean: "9782811607135",
            isbn: "2811607137",
            contributeurs: "Naoko Takeuchi (Auteur principal), Fedoua Lamodiere (Traducteur)",
            format: "Livre poche",
            nbPages: 248,
            editeur: "Pika",
            collection: "PURPLE SHINE",
            largeur: "12 cm",
            longueur: "18 cm",
            epaisseur: "2 cm",
            poids: "0.214 kg",
            impression: "Non",
            saga: "Sailor Moon",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōjo"
        }
    },
    {
        id: 43,
        title: "Jujutsu Kaisen – Tome 1",
        author: "Gege Akutami",
        price: 500,
        category: "manga",
        image: "images/books/jujutsu-kaisen-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Yuji et Sukuna.",
        resume: "Chaque année au Japon, on recense plus de 10 000 morts inexpliquées et portés disparus. Dans la majorité des cas, ce sont les sentiments négatifs des êtres humains qui sont en cause. Yuji Itadori, lycéen et membre du club de spiritisme, va découvrir à ses dépens la réalité des malédictions. Il avale le doigt sectionné d'une créature millénaire et se retrouve possédé par Ryomen Sukuna, le célèbre démon à deux visages.",
        details: {
            ean: "9791032705544",
            isbn: "9791032705544",
            contributeurs: "Gege Akutami (Illustrateur), Gege Akutami (Scénariste), Fedoua Lamodiere (Traducteur)",
            format: "Livre poche",
            nbPages: 188,
            editeur: "Ki-oon",
            collection: "Shōnen",
            largeur: "12 cm",
            longueur: "17.7 cm",
            epaisseur: "1.8 cm",
            poids: "0.175 kg",
            impression: "Non",
            saga: "Jujutsu Kaisen",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 44,
        title: "Vinland Saga – Tome 1",
        author: "Makoto Yukimura",
        price: 550,
        category: "manga",
        image: "images/books/vinland-saga-1.jpg",
        isNew: true,
        isBestseller: false,
        description: "Thorfinn, vengeance et paix.",
        resume: "Depuis qu'Askeladd, un chef de guerre fourbe et sans honneur, a tué son père lorsqu'il était enfant, Thorfinn le suit partout dans le but de se venger. Mais bien qu'il soit devenu un guerrier redoutable, il ne parvient toujours pas à vaincre son ennemi. Au fil des ans, le gentil Thorfinn est devenu froid et solitaire, prisonnier de son passé et incapable d'aller de l'avant. Jusqu'à ce que la vie le force à regarder le Monde différemment.",
        details: {
            ean: "9782351423554",
            isbn: "2351423550",
            contributeurs: "Makoto Yukimura (Auteur principal), Xaviere Daumarie (Traducteur)",
            format: "Livre poche",
            nbPages: 228,
            editeur: "Kurokawa",
            collection: "Vinland saga",
            largeur: "13 cm",
            longueur: "18.4 cm",
            epaisseur: "1.9 cm",
            poids: "0.209 kg",
            impression: "Non",
            saga: "Vinland Saga",
            categories: "Livres, Mangas, Manwha, Man Hua, Seinen, Josei"
        }
    },

    // ============================================================
    // NOUVEAUX LIVRES (45 à 49)
    // ============================================================
    {
        id: 45,
        title: "Hunger Games",
        author: "Suzanne Collins",
        price: 500,
        category: "roman",
        image: "images/books/hunger-games.jpg",
        isNew: true,
        isBestseller: true,
        description: "Katniss et les jeux de la faim.",
        resume: "Dans un futur sombre, sur les ruines des États-Unis, un jeu télévisé est créé pour contrôler le peuple par la terreur. Douze garçons et douze filles tirés au sort participent à cette sinistre téléréalité. Quand sa petite sœur est appelée pour participer aux Hunger Games, Katniss n'hésite pas une seconde. Elle prend sa place, consciente du danger. À seize ans, Katniss a déjà été confrontée plusieurs fois à la mort. Chez elle, survivre est comme une seconde nature.",
        details: {
            ean: "9782266260770",
            isbn: "2266260774",
            contributeurs: "Suzanne Collins (Auteur principal), Guillaume Fournier (Traducteur)",
            format: "Livre poche",
            nbPages: 432,
            editeur: "Pocket Jeunesse",
            collection: "ROMANS CONTES",
            largeur: "11 cm",
            longueur: "17.9 cm",
            epaisseur: "3.1 cm",
            poids: "0.283 kg",
            impression: "Non",
            saga: "Hunger Games",
            categories: "Livres, Jeunesse, Adolescents"
        }
    },
    {
        id: 46,
        title: "Matilda",
        author: "Roald Dahl",
        price: 400,
        category: "roman",
        image: "images/books/matilda.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une petite fille surdouée.",
        resume: "Avant même d'avoir cinq ans, Matilda sait lire et écrire, connaît tout Dickens, tout Hemingway, a dévoré Kipling et Steinbeck. Pourtant son existence est loin d'être facile entre une mère indifférente et un père d'une franche malhonnêteté. Sans oublier mademoiselle Legourdin, la directrice de l'école, qui voue à tous les enfants une haine implacable.",
        details: {
            ean: "9782070512546",
            isbn: "2070512541",
            contributeurs: "Roald Dahl (Auteur principal)",
            format: "Livre poche",
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.5 cm",
            longueur: "17.8 cm",
            epaisseur: "1.2 cm",
            poids: "0.16 kg",
            impression: "Non",
            categories: "Livres, Jeunesse"
        }
    },
    {
        id: 47,
        title: "Le Petit Nicolas",
        author: "René Goscinny",
        price: 350,
        category: "roman",
        image: "images/books/le-petit-nicolas.jpg",
        isNew: true,
        isBestseller: false,
        description: "Les aventures de Nicolas.",
        resume: "Ensemble, le Petit Nicolas et ses copains s'amusent beaucoup. Il faut dire qu'à la maison, au cirque, à la fête foraine ou en retenue, ils ont toujours des idées chouettes comme tout, même si le surveillant, le directeur, la maîtresse, les parents, les voisins et le patron de papa n'ont pas l'air d'être de cet avis... Pourtant, Nicolas et ses amis ne font jamais de bêtises, c'est vrai quoi à la fin !",
        details: {
            ean: "9782070619870",
            isbn: "2070619877",
            contributeurs: "René Goscinny (Auteur principal), Sempé (Auteur principal)",
            format: "Livre poche",
            nbPages: 160,
            editeur: "Gallimard Jeunesse",
            collection: "Folio Junior",
            largeur: "12.4 cm",
            longueur: "17.8 cm",
            epaisseur: "1.1 cm",
            poids: "0.212 kg",
            impression: "Non",
            saga: "Le petit Nicolas : les histoires inédites",
            categories: "Livres, Jeunesse, Romans d'humour, Lectures pour les 7-12 ans"
        }
    },
    {
        id: 48,
        title: "Tous nos lendemains",
        author: "lylyblabla",
        price: 850,
        category: "roman",
        image: "images/books/tous-nos-lendemains.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un roman contemporain.",
        resume: "Il arrive parfois que le destin nous mette face à la bonne personne. Encore faut-il y être prêt. Chris et Chloé s'adorent autant qu'ils s'exaspèrent. Chloé n'a jamais pardonné à Christopher Dean Lewis de lui avoir brisé le cœur quand ils étaient plus jeunes. Lorsque Chloé se retrouve à la rue et que Chris est contraint de l'héberger, les barrières tombent une à une. Mais à vouloir gagner à tout prix, ils risquent de perdre bien plus que ce qu'ils avaient misé.",
        details: {
            ean: "9782755673821",
            isbn: "2755673826",
            contributeurs: "Lylyblabla (Auteur principal)",
            format: "Livre",
            nbPages: 496,
            editeur: "Hugo Roman",
            collection: "New Romance",
            largeur: "13 cm",
            longueur: "20.5 cm",
            epaisseur: "3.5 cm",
            poids: "0.444 kg",
            impression: "Non",
            categories: "Romance et Littérature sentimentale, Littérature française, Livres"
        }
    },
    {
        id: 49,
        title: "Âmes miroirs",
        author: "Olivia Atwater",
        price: 600,
        category: "jeunesse",
        image: "images/books/ames-miroirs.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un roman fantastique.",
        resume: "Faire son entrée dans la haute société londonienne pour trouver un époux n'est pas un problème lorsqu'on est aussi ravissante que Vanessa Ettings. Mais pour sa cousine Theodora, qui n'éprouve plus aucune émotion depuis qu'un faë s'est emparé de la moitié de son âme, ce n'est pas chose aisée. Rien ne pourrait vaincre son indifférence. Mais alors, pourquoi le mauvais caractère du lord Sorcier la perturbe-t-elle autant ?",
        details: {
            ean: "9782226479662",
            isbn: "222647966X",
            contributeurs: "Olivia Atwater (Auteur principal), Nathalie Huet (Traducteur)",
            format: "Livre",
            nbPages: 360,
            editeur: "Albin Michel",
            collection: "Wiz",
            largeur: "14.5 cm",
            longueur: "21.5 cm",
            epaisseur: "2.8 cm",
            poids: "0.482 kg",
            impression: "Non",
            saga: "Chroniques de la cour des faës",
            categories: "Livres, Jeunesse, Adolescents et jeunes adultes, Jeunes adultes"
        }
    },

    // ============================================================
    // MANGAS SUPPLÉMENTAIRES (50 à 67)
    // ============================================================
    {
        id: 50,
        title: "One Piece – Tome 8",
        author: "Eiichiro Oda",
        price: 500,
        category: "manga",
        image: "images/books/one-piece-8.jpg",
        isNew: true,
        isBestseller: true,
        description: "Luffy et son équipage.",
        resume: "Ferme dans ses convictions et ignorant la peur, Luffy défie Don Krieg sans aucune hésitation. Ce combat mettra-t-il un terme à la bataille acharnée qui s'est engagée sur le 'Baratie' ? Pour Sanji, l'heure du départ à l'aventure s'apprête à sonner.",
        details: {
            ean: "9782723489959",
            isbn: "2723489957",
            contributeurs: "Eiichirō Oda (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Glénat",
            collection: "Shōnen",
            largeur: "11.5 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.143 kg",
            impression: "Non",
            saga: "One Piece",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 51,
        title: "One Punch Man – Tome 1",
        author: "Yusuke Murata",
        price: 500,
        category: "manga",
        image: "images/books/one-punch-man-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Saitama, le héros le plus puissant.",
        resume: "Saitama est un jeune homme sans emploi et sans réelle perspective d'avenir, jusqu'au jour où il décide de prendre sa vie en main. Son nouvel objectif : devenir un super-héros. Il s'entraîne alors sans relâche pendant trois ans et devient si puissant qu'il est capable d'éliminer ses adversaires d'un seul coup de poing. On le surnomme désormais One-Punch Man. Mais rapidement, l'euphorie du succès cède place à l'ennui, car lorsqu'on est si fort, les victoires perdent de leur saveur.",
        details: {
            ean: "9782368522257",
            isbn: "2368522255",
            contributeurs: "Yūsuke Murata (Auteur principal), ONE (Auteur principal), Frederic Malet (Traducteur)",
            format: "Livre poche",
            nbPages: 208,
            editeur: "Kurokawa",
            collection: "One-Punch Man",
            largeur: "11.7 cm",
            longueur: "17.8 cm",
            epaisseur: "1.7 cm",
            poids: "0.164 kg",
            impression: "Non",
            saga: "One-Punch Man",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 52,
        title: "Demon Slayer – Tome 9",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-9.jpg",
        isNew: true,
        isBestseller: true,
        description: "Tanjiro affronte les démons.",
        resume: "Tanjiro, Zenitsu et Inosuke sont partis en mission dans le quartier des plaisirs de Yoshiwara avec Tengen Uzui, le pilier du son. En effet, c'est là-bas que les trois kunoichis de Tengen, envoyées en reconnaissance pour débusquer un démon, ont disparu. Pour mener leur enquête dans les maisons des courtisanes, Tanjiro et ses compagnons doivent se déguiser en filles. Mais malgré tous leurs efforts, le démon semble introuvable.",
        details: {
            ean: "9782809487565",
            isbn: "2809487561",
            contributeurs: "Koyoharu Gotôge (Illustrateur), Koyoharu Gotôge (Scénariste), Arnaud Takahashi (Traducteur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            largeur: "11.5 cm",
            longueur: "17.8 cm",
            epaisseur: "1.5 cm",
            poids: "0.152 kg",
            impression: "Non",
            saga: "Demon Slayer",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 53,
        title: "Demon Slayer – Tome 12",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-12.jpg",
        isNew: true,
        isBestseller: true,
        description: "Suite des aventures.",
        resume: "Pour la première fois depuis 113 ans, un démon de la Lune supérieure a été battu. Hors de lui, Muzan convoque les autres démons de la lune supérieure afin de leur ordonner d'intensifier l'attaque contre les pourfendeurs. Lors de la bataille contre Dahi et Gyutaro, le sabre de Tanjiro a été brisé. Tandis qu'il est à la recherche d'un nouveau sabre, Tanjiro visite le village caché des forgerons où se trouve Haganezuka.",
        details: {
            ean: "9782809490084",
            isbn: "2809490082",
            contributeurs: "Koyoharu Gotôge (Auteur principal), Arnaud Takahashi (Traducteur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            collection: "Panini Manga",
            largeur: "11.5 cm",
            longueur: "17.6 cm",
            epaisseur: "2.1 cm",
            poids: "0.153 kg",
            impression: "Non",
            saga: "Demon Slayer",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 54,
        title: "Demon Slayer – Tome 13",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-13.jpg",
        isNew: true,
        isBestseller: true,
        description: "Suite des aventures.",
        resume: "Les lunes supérieures Gyokko et Hantengu ont attaqué le village caché des forgeurs de sabres. Tandis que Tanjiro, Genya et Nezuko font face à Hantengu (qui se dédouble à chaque fois qu'on lui coupe un membre), Tokito, le pilier de la Brume, et Kanroji, le pilier de l'Amour, affrontent Gyokko et son vase tout droit sorti d'un cauchemar.",
        details: {
            ean: "9782809491616",
            isbn: "2809491615",
            contributeurs: "Koyoharu Gotôge (Auteur principal), Xaviere Daumarie (Traducteur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            collection: "Panini Manga",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.7 cm",
            poids: "0.153 kg",
            impression: "Non",
            saga: "Demon Slayer",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 55,
        title: "Demon Slayer – Tome 14",
        author: "Koyoharu Gotouge",
        price: 500,
        category: "manga",
        image: "images/books/demon-slayer-14.jpg",
        isNew: true,
        isBestseller: true,
        description: "Suite des aventures.",
        resume: "A peine Tanjiro et Genya croient-ils avoir vaincu la lune supérieure Hantengu que celui-ci créé un avatar encore plus puissant : Zohakuten, la personnification de la Haine. Heureusement que Mitsuri, le pilier de l'Amour, est là pour leur prêter main-forte. Pendant ce temps, la lune supérieure Gyokko s'apprête à tuer Haganezuka, qui ne peut pas interrompre son travail de polissage sous peine de ruiner à jamais un sabre précieux.",
        details: {
            ean: "9782809492491",
            isbn: "2809492492",
            contributeurs: "Koyoharu Gotôge (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Panini",
            collection: "Panini Manga",
            largeur: "11.5 cm",
            longueur: "17.5 cm",
            epaisseur: "1.6 cm",
            poids: "0.156 kg",
            impression: "Non",
            saga: "Demon Slayer",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 56,
        title: "l'attaque des Titans – Tome 10",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-10.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren et les Titans.",
        resume: "Partis inspecter le mur Rose afin de localiser la brèche à l'origine de la nouvelle intrusion, les membres de la 104e Brigade pensent avoir trouvé un abri sûr dans les ruines de la forteresse d'Utgard et s'apprêtent à prendre un peu de repos pour la nuit. Malheureusement, les Titans, pourtant censés être inactifs après le coucher du soleil, n'ont pas l'intention de leur laisser le moindre répit !",
        details: {
            ean: "9782811615994",
            isbn: "2811615997",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Seinen",
            largeur: "12 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.192 kg",
            impression: "Non",
            saga: "L'Attaque des Titans",
            categories: "Livres, Mangas, Manwha, Man Hua, Seinen, Josei"
        }
    },
    {
        id: 57,
        title: "l'attaque des Titans – Tome 13",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-13.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren et les Titans.",
        resume: "Le Roi a donné l'ordre aux Brigades spéciales de capturer Eren et Christa. De son côté, le Bataillon d'exploration prépare une opération d'envergure : renverser le trône !",
        details: {
            ean: "9782811618810",
            isbn: "2811618813",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Seinen",
            largeur: "12 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.184 kg",
            impression: "Non",
            saga: "L'Attaque des Titans",
            categories: "Livres, Mangas, Manwha, Man Hua, Seinen, Josei"
        }
    },
    {
        id: 58,
        title: "l'attaque des Titans – Tome 14",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-14.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren et les Titans.",
        resume: "Désormais certains que la famille Reiss est bien l'authentique lignée royale, les membres du Bataillon d'exploration s'apprêtent à supplanter le Roi, mais une unité spéciale des Brigades centrales déjoue leur projet en ravissant Historia et Eren !",
        details: {
            ean: "9782811620943",
            isbn: "281162094X",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Seinen",
            largeur: "12 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.192 kg",
            impression: "Non",
            saga: "L'Attaque des Titans",
            categories: "Livres, Mangas, Manwha, Man Hua, Seinen, Josei"
        }
    },
    {
        id: 59,
        title: "l'attaque des Titans – Tome 15",
        author: "Hajime Isayama",
        price: 500,
        category: "manga",
        image: "images/books/attack-on-titan-15.jpg",
        isNew: true,
        isBestseller: true,
        description: "Eren et les Titans.",
        resume: "Alors que les Brigades spéciales sont sur le point de mettre la main sur Eren, le Bataillon d'exploration fait son apparition pour déjouer leurs plans. Les deux camps s'affrontent dans une bataille décisive qui pourrait changer le cours de l'histoire.",
        details: {
            ean: "9782811620950",
            isbn: "2811620958",
            contributeurs: "Hajime Isayama (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Seinen",
            largeur: "12 cm",
            longueur: "18 cm",
            epaisseur: "1.5 cm",
            poids: "0.192 kg",
            impression: "Non",
            saga: "L'Attaque des Titans",
            categories: "Livres, Mangas, Manwha, Man Hua, Seinen, Josei"
        }
    },
    {
        id: 60,
        title: "Hunter x Hunter – Tome 5",
        author: "Yoshihiro Togashi",
        price: 500,
        category: "manga",
        image: "images/books/hunter-x-hunter-5.jpg",
        isNew: true,
        isBestseller: true,
        description: "Gon et ses amis.",
        resume: "Kirua sort de ses gonds ! Le résultat n'est pas beau à voir : un innocent participant en fera les frais. On fait connaissance avec le frère aîné de Kirua qui n'a pas l'air commode et semble bien connaître Hisoka.",
        details: {
            ean: "9782871292708",
            isbn: "2871292701",
            contributeurs: "Yoshihiro Togashi (Auteur principal)",
            format: "Livre poche",
            nbPages: 190,
            editeur: "Kana",
            collection: "Shōnen",
            largeur: "11.8 cm",
            longueur: "17.5 cm",
            epaisseur: "1.4 cm",
            poids: "0.136 kg",
            impression: "Non",
            saga: "Hunter X Hunter",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 61,
        title: "Hunter x Hunter – Tome 7",
        author: "Yoshihiro Togashi",
        price: 500,
        category: "manga",
        image: "images/books/hunter-x-hunter-7.jpg",
        isNew: true,
        isBestseller: true,
        description: "Gon et ses amis.",
        resume: "Fin de l'interdiction d'utiliser le 'nen' ! Promesse tenue pendant 2 mois ! Le véritable entraînement peut commencer ! Hisoka a exigé de Gon qu'il gagne un match dans son groupe du 200e étage avant de pouvoir l'affronter. Mais les membres de ce groupe ont pour cible les nouveaux venus.",
        details: {
            ean: "9782871293224",
            isbn: "2871293228",
            contributeurs: "Yoshihiro Togashi (Auteur principal)",
            format: "Livre poche",
            nbPages: 190,
            editeur: "Kana",
            collection: "Shōnen",
            largeur: "11.7 cm",
            longueur: "17.5 cm",
            epaisseur: "1.5 cm",
            poids: "0.134 kg",
            impression: "Non",
            saga: "Hunter X Hunter",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 62,
        title: "Naruto – Tome 10",
        author: "Masashi Kishimoto",
        price: 500,
        category: "manga",
        image: "images/books/naruto-10.jpg",
        isNew: true,
        isBestseller: true,
        description: "Naruto et ses compagnons.",
        resume: "Dans le village de Konoha sévit Naruto, le pire garnement de l'école des ninjas ! Son passe-temps favori ? Faire les quatre cents coups ! Mais Naruto a aussi un rêve démesuré : devenir le plus puissant ninja de son village. 'Un jour, je deviendrai Hokage, moi aussi !'",
        details: {
            ean: "9782505115045",
            isbn: "2505115044",
            contributeurs: "Masashi Kishimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 372,
            editeur: "Kana",
            collection: "Shōnen",
            largeur: "14.5 cm",
            longueur: "21.3 cm",
            epaisseur: "3.4 cm",
            poids: "0.426 kg",
            impression: "Non",
            saga: "Naruto",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 63,
        title: "Naruto – Tome 11",
        author: "Masashi Kishimoto",
        price: 500,
        category: "manga",
        image: "images/books/naruto-11.jpg",
        isNew: true,
        isBestseller: true,
        description: "Naruto et ses compagnons.",
        resume: "La suite des aventures de Naruto, le ninja le plus fou de Konoha ! Naruto et ses compagnons continuent leur entraînement pour devenir des ninjas d'élite, affrontant de nouveaux défis et de redoutables ennemis sur leur chemin.",
        details: {
            ean: "9782505115052",
            isbn: "2505115052",
            contributeurs: "Masashi Kishimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 400,
            editeur: "Kana",
            collection: "Shōnen",
            largeur: "14.5 cm",
            longueur: "21.3 cm",
            epaisseur: "3.7 cm",
            poids: "0.454 kg",
            impression: "Non",
            saga: "Naruto",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 64,
        title: "Blue Lock – Tome 1",
        author: "Muneyuki Kaneshiro",
        price: 500,
        category: "manga",
        image: "images/books/blue-lock-1.jpg",
        isNew: true,
        isBestseller: true,
        description: "Le football version survival.",
        resume: "Coupe du monde 2018, l'équipe de football du Japon est éliminée en huitièmes de finale. Ce nouvel échec incite l'Union japonaise de football à fonder le 'Blue Lock' : un centre de formation révolutionnaire rassemblant les 300 meilleurs attaquants lycéens du pays. L'objectif : détecter l'unique attaquant qui écrasera tous ses rivaux par son talent et son hyper-individualisme !",
        details: {
            ean: "9782811650254",
            isbn: "2811650253",
            contributeurs: "Muneyuki Kaneshiro (Auteur principal), Yûsuke Nomura (Auteur principal)",
            format: "Livre poche",
            nbPages: 208,
            editeur: "Pika",
            collection: "Shōnen",
            largeur: "12 cm",
            longueur: "18 cm",
            epaisseur: "1.6 cm",
            poids: "0.175 kg",
            impression: "Non",
            saga: "Blue Lock",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 65,
        title: "Blue Lock – Tome 2",
        author: "Muneyuki Kaneshiro",
        price: 500,
        category: "manga",
        image: "images/books/blue-lock-2.jpg",
        isNew: true,
        isBestseller: true,
        description: "Le football version survival.",
        resume: "En dépit des critiques enflammées du grand public et des médias, le projet Blue Lock a finalement été lancé. Ayant survécu au premier écrémage, Yoichi Isagi se retrouve dans l'équipe Z, formée exclusivement d'attaquants. Avec elle, il devra lutter dans une poule de cinq équipes où seules les deux meilleures resteront en lice. L'équipe Z n'aura qu'un seul moyen de survie : découvrir une arme capable de faire éclore l'égo de chacun !",
        details: {
            ean: "9782811661274",
            isbn: "2811661271",
            contributeurs: "Muneyuki Kaneshiro (Auteur principal), Yûsuke Nomura (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Pika",
            collection: "Shōnen",
            largeur: "12 cm",
            longueur: "18 cm",
            epaisseur: "1.6 cm",
            poids: "0.167 kg",
            impression: "Non",
            saga: "Blue Lock",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen"
        }
    },
    {
        id: 66,
        title: "Chainsaw Man – Tome 7",
        author: "Tatsuki Fujimoto",
        price: 500,
        category: "manga",
        image: "images/books/chainsaw-man-7.jpg",
        isNew: true,
        isBestseller: true,
        description: "Denji et ses démons.",
        resume: "Suite aux attaques dont ses agents ont été les cibles, la Sécurité Publique a décidé de contre-attaquer en engageant toutes ses forces dans la bataille ! Dévoré par les flammes de la vengeance, Aki se retrouve confronté à Ghost, le puissant démon qu'employait autrefois l'agent Himeno. De son côté, Denji affronte une nouvelle fois Samouraï Sword ! Tronçonneuse contre katana... quelle lame aura le dessus ?",
        details: {
            ean: "9782820340672",
            isbn: "2820340679",
            contributeurs: "Tatsuki Fujimoto (Auteur principal), Sebastien Ludmann (Traducteur)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Crunchyroll",
            largeur: "11.3 cm",
            longueur: "17.6 cm",
            epaisseur: "1.4 cm",
            poids: "0.142 kg",
            impression: "Non",
            saga: "Chainsaw Man",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen, Seinen, Josei"
        }
    },
    {
        id: 67,
        title: "Chainsaw Man – Tome 8",
        author: "Tatsuki Fujimoto",
        price: 500,
        category: "manga",
        image: "images/books/chainsaw-man-8.jpg",
        isNew: true,
        isBestseller: true,
        description: "Denji et ses démons.",
        resume: "Suite aux attaques dont ses agents ont été les cibles, la Sécurité Publique a décidé de contre-attaquer en engageant toutes ses forces dans la bataille ! Dévoré par les flammes de la vengeance, Aki se retrouve confronté à Ghost, le puissant démon qu'employait autrefois l'agent Himeno. De son côté, Denji affronte une nouvelle fois Samouraï Sword ! Tronçonneuse contre katana... quelle lame aura le dessus ?",
        details: {
            ean: "9782820340849",
            isbn: "2820340849",
            contributeurs: "Tatsuki Fujimoto (Auteur principal)",
            format: "Livre poche",
            nbPages: 192,
            editeur: "Crunchyroll",
            collection: "Shonen up!",
            largeur: "11.5 cm",
            longueur: "18.3 cm",
            epaisseur: "1.3 cm",
            poids: "0.132 kg",
            impression: "Non",
            saga: "Chainsaw Man",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen, Seinen, Josei"
        }
    },

    // ============================================================
    // LIVRES JEUNESSE / ALBUMS (68 à 78)
    // ============================================================
    {
        id: 68,
        title: "Je t'aimerai toujours, quoi qu'il arrive...",
        author: "Debi Gliori",
        price: 500,
        category: "jeunesse",
        image: "images/books/je-taimerai-toujours.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un album tendre sur l'amour inconditionnel.",
        resume: "Petit Renard est inquiet car il craint de ne plus être aimé de sa maman s'il fait trop de bêtises... Mais sa maman lui explique que leur amour durera toujours... quoi qu'il arrive ! Un album pour rassurer tous les enfants.",
        details: {
            ean: "9782013944762",
            isbn: "2013944764",
            contributeurs: "Debi Gliori (Auteur principal)",
            format: "Livre",
            nbPages: 32,
            editeur: "Gautier Languereau",
            collection: "TU ME LIS UNE HISTOIRE ?",
            largeur: "16 cm",
            longueur: "18 cm",
            epaisseur: "5 mm",
            poids: "0.1 kg",
            impression: "Non",
            categories: "Livres, Albums illustrés, Albums"
        }
    },
    {
        id: 69,
        title: "Le monstre des couleurs : la couleur des émotions",
        author: "Anna Llenas",
        price: 1500,
        category: "jeunesse",
        image: "images/books/le-monstre-des-couleurs.jpg",
        isNew: true,
        isBestseller: true,
        description: "Un livre animé pour aider les enfants à identifier leurs émotions.",
        resume: "Le monstre des couleurs se sent tout barbouillé, aujourd'hui. Ses émotions sont sens dessus dessous ! Il ne comprend pas ce qui lui arrive. Réussira-t-il à mettre de l'ordre dans son cœur et à retrouver son équilibre ? Un livre tout animé pour découvrir ses émotions.",
        details: {
            ean: "9791026400134",
            isbn: "9791026400134",
            contributeurs: "Anna Llenas (Auteur principal)",
            format: "Livre Pop-Up",
            nbPages: 22,
            editeur: "Glénat Jeunesse",
            largeur: "27 cm",
            longueur: "23.8 cm",
            epaisseur: "2.2 cm",
            poids: "0.705 kg",
            impression: "Non",
            categories: "Livres, Livres animés et pop-up, Jeunesse"
        }
    },
    {
        id: 70,
        title: "Grosse Colère",
        author: "Mireille d'Allancé",
        price: 500,
        category: "jeunesse",
        image: "images/books/grosse-colere.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une histoire sur la colère et comment l'apprivoiser.",
        resume: "Robert a passé une très mauvaise journée. Il n'est pas de bonne humeur et en plus, son papa l'a envoyé dans sa chambre. Alors Robert sent tout à coup monter une chose terrible : la colère...",
        details: {
            ean: "9782211061773",
            isbn: "221106177X",
            contributeurs: "Mireille d' Allancé (Auteur principal)",
            format: "Livre poche",
            nbPages: 32,
            editeur: "L'École des Loisirs",
            collection: "Les lutins",
            largeur: "15 cm",
            longueur: "19 cm",
            epaisseur: "2 mm",
            poids: "0.084 kg",
            impression: "Non",
            categories: "Livres, Albums illustrés, Albums"
        }
    },
    {
        id: 71,
        title: "Au revoir Blaireau",
        author: "Susan Varley",
        price: 500,
        category: "jeunesse",
        image: "images/books/au-revoir-blaireau.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un album poignant sur le deuil et l'amitié.",
        resume: "Un matin, les amis de Blaireau se rassemblent devant sa porte. Ils s'inquiètent parce que leur vieil ami n'est pas sorti pour leur dire bonjour comme d'habitude... Un livre plein d'émotion et d'espoir, à lire ensemble.",
        details: {
            ean: "9782075155120",
            isbn: "2075155127",
            contributeurs: "Susan Varley (Auteur principal)",
            format: "Livre",
            nbPages: 32,
            editeur: "Gallimard Jeunesse",
            collection: "L'heure des histoires",
            largeur: "16 cm",
            longueur: "20.6 cm",
            epaisseur: "4 mm",
            poids: "0.098 kg",
            impression: "Non",
            categories: "Livres, Jeunesse, Premières lectures, Albums illustrés"
        }
    },
    {
        id: 72,
        title: "La boite à étoiles",
        author: "Jerome Camil",
        price: 1100,
        category: "jeunesse",
        image: "images/books/la-boite-a-etoiles.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une histoire poétique sur les rêves et l'imagination.",
        resume: "Un cadeau fait main, ça vaut combien d'objets achetés ? Accompagné de son meilleur copain, un jeune écureuil se met en quête d'une étoile pour sa maman. Elle est morte et, depuis, le temps s'est arrêté pour lui. Il lui tient à cœur, ce cadeau ! Pour essayer de donner du sens à ce qui n'en a pas. Pour dire au revoir. Pour que la vie continue.",
        details: {
            ean: "9782874266690",
            isbn: "2874266698",
            contributeurs: "Jerome Camil (Auteur principal)",
            format: "Livre",
            nbPages: 48,
            editeur: "ALICE",
            collection: "Albums",
            largeur: "22 cm",
            longueur: "30 cm",
            epaisseur: "1.3 cm",
            poids: "0.49 kg",
            impression: "Non",
            categories: "Albums illustrés, Premiers albums, Livres, Livres pour grandir"
        }
    },
    {
        id: 73,
        title: "Une surprise pour maman",
        author: "Karine-Marie Amiot, Diane De Saint-exupery",
        price: 850,
        category: "jeunesse",
        image: "images/books/une-surprise-pour-maman.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un album pour célébrer l'amour filial.",
        resume: "Dans le sillage des Belles Histoires de grand-mère, cette nouvelle collection parlera aux plus jeunes d'événements de la vie d'une famille d'aujourd'hui. Avec des textes pleins de poésie de Karine-Marie Amiot et des illustrations délicates de Diane de Saint-Exupéry, cet album raconte, de façon tendre et joyeuse, les préparatifs de la Fête des mères.",
        details: {
            ean: "9782728934829",
            isbn: "2728934827",
            contributeurs: "Karine-Marie Amiot (Auteur principal), Diane De Saint-exupery (Auteur principal)",
            format: "Livre",
            nbPages: 32,
            editeur: "MAME",
            collection: "La famille lapi",
            largeur: "20.8 cm",
            longueur: "21.1 cm",
            epaisseur: "9 mm",
            poids: "0.266 kg",
            impression: "Non",
            categories: "Albums illustrés, Premiers albums, Livres, Albums"
        }
    },
    {
        id: 74,
        title: "Petit amour",
        author: "Nadine Brun-Cosme, Marion Cocklico",
        price: 800,
        category: "jeunesse",
        image: "images/books/petit-amour.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un livre tendre sur les premiers émois.",
        resume: "Une histoire tendre pour aider votre tout-petit à reconnaître ses émotions, et pour partager avec lui un moment de bonheur.",
        details: {
            ean: "9782215135968",
            isbn: "2215135964",
            contributeurs: "Nadine Brun-Cosme (Auteur principal), Marion Cocklico (Auteur principal)",
            format: "Livre",
            nbPages: 12,
            editeur: "Fleurus",
            collection: "Petit doux",
            largeur: "17.5 cm",
            longueur: "17.6 cm",
            epaisseur: "1.5 cm",
            poids: "0.315 kg",
            impression: "Non",
            categories: "Livres, Tout-petits - de 0 à 3 ans, Livres pour grandir, Albums"
        }
    },
    {
        id: 75,
        title: "Dans le magasin des mamans j'aurais choisi toi",
        author: "Mathou",
        price: 1100,
        category: "jeunesse",
        image: "images/books/dans-le-magasin-des-mamans.jpg",
        isNew: true,
        isBestseller: false,
        description: "Un message d'amour pour sa maman.",
        resume: "Quand nos enfants posent leur regard malicieux et clairvoyant sur nos imperfections de parents... Une déclaration d'amour espiègle, drôle et totalement décomplexante. 'Tu dis toujours que tu es plus fatiguée qu'avant. Tu m'habilles dès la rentrée comme si on vivait au Pôle Nord. Et pourtant : moi, dans le magasin des mamans, j'aurais choisi toi.'",
        details: {
            ean: "9782221263914",
            isbn: "222126391X",
            contributeurs: "Mathou (Auteur principal)",
            format: "Livre",
            nbPages: 40,
            editeur: "Robert Laffont",
            largeur: "21.2 cm",
            longueur: "26 cm",
            epaisseur: "1 cm",
            poids: "0.354 kg",
            impression: "Non",
            categories: "Livres, Albums illustrés, Premiers albums"
        }
    },
    {
        id: 76,
        title: "Les Schtroumpfs Tome 39 : Les Schtroumpfs et la tempête blanche",
        author: "Peyo, Alain Jost, Thierry Culliford",
        price: 1000,
        category: "bd",
        image: "images/books/schtroumpfs-tome39.jpg",
        isNew: true,
        isBestseller: false,
        description: "Une aventure des Schtroumpfs dans la neige.",
        resume: "Comme chaque année, les premiers frimas sont attendus de pied ferme par les Schtroumpfs, qui se sont bien préparés. Mais personne ne s'attendait à un tel blizzard ! Partis tester une nouvelle luge, les Schtroumpfs Farceur, à Lunettes et Bricoleur se retrouvent coupés d'un village qui s'organise tant bien que mal. Ils trouvent refuge chez un sourcier acariâtre, qui a pourtant tout fait pour fuir la vie en communauté. Et si le salut des uns schtroumpfait par celui des autres ?",
        details: {
            ean: "9782803680047",
            isbn: "2803680041",
            contributeurs: "Peyo (Auteur principal), Alain Jost (Auteur principal), Thierry Culliford (Auteur principal)",
            format: "Livre",
            nbPages: 48,
            editeur: "Le Lombard",
            largeur: "22.2 cm",
            longueur: "29.5 cm",
            epaisseur: "1.1 cm",
            poids: "0.378 kg",
            impression: "Non",
            saga: "Les Schtroumpfs",
            categories: "Livres, BD"
        }
    },
    {
        id: 77,
        title: "Pokémon - La grande aventure Tome 1",
        author: "Hidenori Kusaka, Mato",
        price: 800,
        category: "manga",
        image: "images/books/pokemon-grande-aventure-t1.jpg",
        isNew: true,
        isBestseller: false,
        description: "Les aventures de Pokémon en version manga.",
        resume: "Suivez la grande aventure de Rouge et Bleu, deux jeunes Dresseurs qui se sont promis de réaliser leurs rêves ! Rouge est un jeune garçon plein d'ambition et de fougue. Sa plus grande fierté : être considéré comme le meilleur Dresseur de Pokémon des environs de Bourg Palette ! Le Professeur Chen va le convaincre de partir à la découverte de nouveaux Pokémon pour compléter le fameux Pokédex.",
        details: {
            ean: "9782368520130",
            isbn: "2368520139",
            contributeurs: "Hidenori Kusaka (Auteur principal), Mato (Auteur principal)",
            format: "Livre poche",
            nbPages: 512,
            editeur: "Kurokawa",
            collection: "Pokémon",
            largeur: "12.8 cm",
            longueur: "18.3 cm",
            epaisseur: "4 cm",
            poids: "0.427 kg",
            impression: "Non",
            saga: "Pokémon",
            categories: "Livres, Mangas, Manwha, Man Hua, Shōnen, Kodomo"
        }
    },
    {
        id: 78,
        title: "Les aventures de Tintin, le secret de la licorne",
        author: "Steven Spielberg (réalisateur)",
        price: 400,
        category: "bd",
        image: "images/books/tintin-secret-licorne.jpg",
        isNew: false,
        isBestseller: false,
        description: "Le film d'animation adapté de la BD d'Hergé.",
        resume: "Parce qu'il achète la maquette d'un bateau appelé la Licorne, Tintin, un jeune reporter, se retrouve entraîné dans une fantastique aventure à la recherche d'un fabuleux secret. Avec l'aide de Milou, du capitaine Haddock et des détectives Dupond et Dupont, Tintin va parcourir la moitié de la planète dans une course au trésor à la recherche d'une épave engloutie.",
        details: {
            ean: "3333297719186",
            contributeurs: "Steven Spielberg (Realisateur), Jamie Bell (Acteur), Andy Serkis (Acteur), Daniel Craig (Acteur), Sony Pictures Home Entertainment (Producteur)",
            format: "DVD",
            nbPages: 1,
            editeur: "Sony Pictures Home Entertainment",
            genre: "Aventure",
            poids: "0.25 kg",
            duree: "107 min",
            impression: "Non",
            categories: "Vidéo, Jeunesse - Animation, Walt Disney"
        }
    }
];
